import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'sw' | 'ta' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Additional translations for cow management page
const cowManagementTranslations: Record<Language, Record<string, string>> = {
  en: {
    cowManagementDesc: 'Manage your herd information with real-time sensor updates',
    editCow: 'Edit Cow',
    addNewCow: 'Add New Cow',
    updateCow: 'Update Cow',
    noCowsYet: 'No cows yet',
    noCowsFound: 'No cows found',
    addFirstCow: 'Add Your First Cow',
    addFirstCowDesc: 'Add your first cow to get started',
    tryDifferentSearch: 'Try a different search term',
    searchByNameOrTag: 'Search by name or tag...',
    today: 'Today',
    total: 'Total',
    latestSensorData: 'Latest Sensor Data',
    sensor: 'Sensor',
    reading: 'Reading',
    heatIntensity: 'Heat Intensity',
    aiConfidence: 'AI Confidence',
    detected: 'Detected',
    born: 'Born',
    milk: 'Milk',
    health: 'Health',
    pregnant: 'Pregnant',
    sick: 'Sick',
    // Analytics
    analyticsDashboard: 'Analytics Dashboard',
    analyticsDesc: 'Track your herd\'s breeding performance and milk production',
    totalCowsLabel: 'Total Cows',
    heatDetectionsLabel: 'Heat Detections',
    thirtyDayMilk: '30-Day Milk',
    avgPerDay: 'Avg/Day',
    inseminations: 'Inseminations',
    dailyMilkProduction: 'Daily Milk Production (Last 14 Days)',
    herdStatusDistribution: 'Herd Status Distribution',
    monthlyBreedingTrends: 'Monthly Breeding Trends',
    activityOverview: 'Activity Overview (Last 6 Months)',
    calvings: 'Calvings',
    noDataAvailable: 'No data available',
    noMilkData: 'No milk production data available',
    // Additional page descriptions
    heatDetectionDesc: 'Monitor and track heat cycles with sensor data',
    breedingCalendarDesc: 'Track breeding events and optimal timing',
    staffAttendanceDesc: 'Track staff attendance with biometric verification',
    // Health Records Dialog
    healthRecordsTitle: 'Health Records',
    addHealthRecord: 'Add Health Record',
    date: 'Date',
    recordType: 'Record Type',
    diagnosis: 'Diagnosis',
    treatment: 'Treatment',
    medications: 'Medications',
    veterinarian: 'Veterinarian',
    cost: 'Cost',
    followUpDate: 'Follow-up Date',
    saveRecord: 'Save Record',
    noHealthRecords: 'No health records yet',
    failedLoadHealth: 'Failed to load health records',
    healthRecordAdded: 'Health record added',
    failedAddHealth: 'Failed to add health record',
    vet: 'Vet',
    followUp: 'Follow-up',
    enterDiagnosis: 'Enter diagnosis',
    vetName: 'Vet name',
    describeTreatment: 'Describe treatment',
    listMedications: 'List medications',
    additionalNotes: 'Additional notes...',
    // Milk Production Dialog
    milkProductionTitle: 'Milk Production',
    recordManualEntry: 'Record Manual Entry',
    quantityLiters: 'Quantity (Liters)',
    qualityGrade: 'Quality Grade',
    fatPercentage: 'Fat %',
    proteinPercentage: 'Protein %',
    noMilkRecords: 'No milk production records yet',
    failedLoadMilk: 'Failed to load milk production records',
    milkRecordAdded: 'Milk production recorded',
    failedAddMilk: 'Failed to add milk production record',
    avgSession: 'Avg/Session',
    thirtyDayTotalLabel: '30 Day Total',
    productionTrend: 'Production Trend (Last 14 Records)',
    liters: 'Liters',
    grade: 'Grade',
    auto: 'Auto',
    newMilkRecorded: 'New milk production recorded by sensor',
    // Record types
    vaccination: 'Vaccination',
    checkup: 'Checkup',
    surgery: 'Surgery',
    deworming: 'Deworming',
    hoofTrimming: 'Hoof Trimming',
    pregnancyCheck: 'Pregnancy Check',
    other: 'Other',
  },
  es: {
    cowManagementDesc: 'Gestione la información de su rebaño con actualizaciones de sensores en tiempo real',
    editCow: 'Editar Vaca',
    addNewCow: 'Agregar Nueva Vaca',
    updateCow: 'Actualizar Vaca',
    noCowsYet: 'Sin vacas aún',
    noCowsFound: 'No se encontraron vacas',
    addFirstCow: 'Agregar Su Primera Vaca',
    addFirstCowDesc: 'Agregue su primera vaca para comenzar',
    tryDifferentSearch: 'Intente un término de búsqueda diferente',
    searchByNameOrTag: 'Buscar por nombre o etiqueta...',
    today: 'Hoy',
    total: 'Total',
    latestSensorData: 'Últimos Datos del Sensor',
    sensor: 'Sensor',
    reading: 'Lectura',
    heatIntensity: 'Intensidad de Celo',
    aiConfidence: 'Confianza IA',
    detected: 'Detectado',
    born: 'Nacido',
    milk: 'Leche',
    health: 'Salud',
    pregnant: 'Preñada',
    sick: 'Enferma',
    analyticsDashboard: 'Panel de Análisis',
    analyticsDesc: 'Seguimiento del rendimiento reproductivo y producción de leche',
    totalCowsLabel: 'Total de Vacas',
    heatDetectionsLabel: 'Detecciones de Celo',
    thirtyDayMilk: 'Leche 30 Días',
    avgPerDay: 'Prom/Día',
    inseminations: 'Inseminaciones',
    dailyMilkProduction: 'Producción Diaria de Leche (Últimos 14 Días)',
    herdStatusDistribution: 'Distribución del Estado del Rebaño',
    monthlyBreedingTrends: 'Tendencias Mensuales de Reproducción',
    activityOverview: 'Resumen de Actividad (Últimos 6 Meses)',
    calvings: 'Partos',
    noDataAvailable: 'Sin datos disponibles',
    noMilkData: 'Sin datos de producción de leche',
    heatDetectionDesc: 'Monitorear y rastrear ciclos de celo con datos de sensores',
    breedingCalendarDesc: 'Seguimiento de eventos reproductivos y tiempo óptimo',
    staffAttendanceDesc: 'Seguimiento de asistencia del personal con verificación biométrica',
    healthRecordsTitle: 'Registros de Salud',
    addHealthRecord: 'Agregar Registro de Salud',
    date: 'Fecha',
    recordType: 'Tipo de Registro',
    diagnosis: 'Diagnóstico',
    treatment: 'Tratamiento',
    medications: 'Medicamentos',
    veterinarian: 'Veterinario',
    cost: 'Costo',
    followUpDate: 'Fecha de Seguimiento',
    saveRecord: 'Guardar Registro',
    noHealthRecords: 'Sin registros de salud aún',
    failedLoadHealth: 'Error al cargar registros de salud',
    healthRecordAdded: 'Registro de salud agregado',
    failedAddHealth: 'Error al agregar registro de salud',
    vet: 'Vet',
    followUp: 'Seguimiento',
    enterDiagnosis: 'Ingrese diagnóstico',
    vetName: 'Nombre del veterinario',
    describeTreatment: 'Describa el tratamiento',
    listMedications: 'Liste medicamentos',
    additionalNotes: 'Notas adicionales...',
    milkProductionTitle: 'Producción de Leche',
    recordManualEntry: 'Registrar Entrada Manual',
    quantityLiters: 'Cantidad (Litros)',
    qualityGrade: 'Grado de Calidad',
    fatPercentage: 'Grasa %',
    proteinPercentage: 'Proteína %',
    noMilkRecords: 'Sin registros de producción de leche aún',
    failedLoadMilk: 'Error al cargar registros de producción de leche',
    milkRecordAdded: 'Producción de leche registrada',
    failedAddMilk: 'Error al agregar registro de producción de leche',
    avgSession: 'Prom/Sesión',
    thirtyDayTotalLabel: 'Total 30 Días',
    productionTrend: 'Tendencia de Producción (Últimos 14 Registros)',
    liters: 'Litros',
    grade: 'Grado',
    auto: 'Auto',
    newMilkRecorded: 'Nueva producción de leche registrada por sensor',
    vaccination: 'Vacunación',
    checkup: 'Chequeo',
    surgery: 'Cirugía',
    deworming: 'Desparasitación',
    hoofTrimming: 'Recorte de Pezuñas',
    pregnancyCheck: 'Chequeo de Preñez',
    other: 'Otro',
  },
  fr: {
    cowManagementDesc: 'Gérez les informations de votre troupeau avec des mises à jour en temps réel',
    editCow: 'Modifier la Vache',
    addNewCow: 'Ajouter une Nouvelle Vache',
    updateCow: 'Mettre à Jour la Vache',
    noCowsYet: 'Pas encore de vaches',
    noCowsFound: 'Aucune vache trouvée',
    addFirstCow: 'Ajouter Votre Première Vache',
    addFirstCowDesc: 'Ajoutez votre première vache pour commencer',
    tryDifferentSearch: 'Essayez un autre terme de recherche',
    searchByNameOrTag: 'Rechercher par nom ou étiquette...',
    today: 'Aujourd\'hui',
    total: 'Total',
    latestSensorData: 'Dernières Données du Capteur',
    sensor: 'Capteur',
    reading: 'Lecture',
    heatIntensity: 'Intensité de Chaleur',
    aiConfidence: 'Confiance IA',
    detected: 'Détecté',
    born: 'Né',
    milk: 'Lait',
    health: 'Santé',
    pregnant: 'Gestante',
    sick: 'Malade',
    analyticsDashboard: 'Tableau de Bord Analytique',
    analyticsDesc: 'Suivez les performances de reproduction et la production laitière',
    totalCowsLabel: 'Total des Vaches',
    heatDetectionsLabel: 'Détections de Chaleur',
    thirtyDayMilk: 'Lait 30 Jours',
    avgPerDay: 'Moy/Jour',
    inseminations: 'Inséminations',
    dailyMilkProduction: 'Production Laitière Quotidienne (14 Derniers Jours)',
    herdStatusDistribution: 'Distribution du Statut du Troupeau',
    monthlyBreedingTrends: 'Tendances Mensuelles de Reproduction',
    activityOverview: 'Aperçu de l\'Activité (6 Derniers Mois)',
    calvings: 'Vêlages',
    noDataAvailable: 'Aucune donnée disponible',
    noMilkData: 'Aucune donnée de production laitière',
    heatDetectionDesc: 'Surveiller et suivre les cycles de chaleur avec les données des capteurs',
    breedingCalendarDesc: 'Suivre les événements de reproduction et le moment optimal',
    staffAttendanceDesc: 'Suivi de la présence du personnel avec vérification biométrique',
    healthRecordsTitle: 'Dossiers de Santé',
    addHealthRecord: 'Ajouter un Dossier de Santé',
    date: 'Date',
    recordType: 'Type de Dossier',
    diagnosis: 'Diagnostic',
    treatment: 'Traitement',
    medications: 'Médicaments',
    veterinarian: 'Vétérinaire',
    cost: 'Coût',
    followUpDate: 'Date de Suivi',
    saveRecord: 'Enregistrer le Dossier',
    noHealthRecords: 'Aucun dossier de santé',
    failedLoadHealth: 'Échec du chargement des dossiers de santé',
    healthRecordAdded: 'Dossier de santé ajouté',
    failedAddHealth: 'Échec de l\'ajout du dossier de santé',
    vet: 'Vét',
    followUp: 'Suivi',
    enterDiagnosis: 'Entrez le diagnostic',
    vetName: 'Nom du vétérinaire',
    describeTreatment: 'Décrivez le traitement',
    listMedications: 'Listez les médicaments',
    additionalNotes: 'Notes supplémentaires...',
    milkProductionTitle: 'Production Laitière',
    recordManualEntry: 'Enregistrer une Entrée Manuelle',
    quantityLiters: 'Quantité (Litres)',
    qualityGrade: 'Grade de Qualité',
    fatPercentage: 'Matière Grasse %',
    proteinPercentage: 'Protéine %',
    noMilkRecords: 'Aucun enregistrement de production laitière',
    failedLoadMilk: 'Échec du chargement des enregistrements de production laitière',
    milkRecordAdded: 'Production laitière enregistrée',
    failedAddMilk: 'Échec de l\'ajout de l\'enregistrement de production laitière',
    avgSession: 'Moy/Session',
    thirtyDayTotalLabel: 'Total 30 Jours',
    productionTrend: 'Tendance de Production (14 Derniers Enregistrements)',
    liters: 'Litres',
    grade: 'Grade',
    auto: 'Auto',
    newMilkRecorded: 'Nouvelle production laitière enregistrée par capteur',
    vaccination: 'Vaccination',
    checkup: 'Contrôle',
    surgery: 'Chirurgie',
    deworming: 'Vermifugeage',
    hoofTrimming: 'Parage des Sabots',
    pregnancyCheck: 'Contrôle de Gestation',
    other: 'Autre',
  },
  sw: {
    cowManagementDesc: 'Simamia habari za mifugo yako na sasisho za sensori za wakati halisi',
    editCow: 'Hariri Ng\'ombe',
    addNewCow: 'Ongeza Ng\'ombe Mpya',
    updateCow: 'Sasisha Ng\'ombe',
    noCowsYet: 'Hakuna ng\'ombe bado',
    noCowsFound: 'Hakuna ng\'ombe waliopatikana',
    addFirstCow: 'Ongeza Ng\'ombe Wako wa Kwanza',
    addFirstCowDesc: 'Ongeza ng\'ombe wako wa kwanza kuanza',
    tryDifferentSearch: 'Jaribu neno lingine la kutafuta',
    searchByNameOrTag: 'Tafuta kwa jina au lebo...',
    today: 'Leo',
    total: 'Jumla',
    latestSensorData: 'Data ya Sensori ya Hivi Karibuni',
    sensor: 'Sensori',
    reading: 'Usomaji',
    heatIntensity: 'Ukali wa Joto',
    aiConfidence: 'Uhakika wa AI',
    detected: 'Iligunduliwa',
    born: 'Alizaliwa',
    milk: 'Maziwa',
    health: 'Afya',
    pregnant: 'Mjamzito',
    sick: 'Mgonjwa',
    analyticsDashboard: 'Dashibodi ya Uchambuzi',
    analyticsDesc: 'Fuatilia utendaji wa uzazi na uzalishaji wa maziwa',
    totalCowsLabel: 'Jumla ya Ng\'ombe',
    heatDetectionsLabel: 'Ugunduzi wa Joto',
    thirtyDayMilk: 'Maziwa Siku 30',
    avgPerDay: 'Wast/Siku',
    inseminations: 'Upandishaji',
    dailyMilkProduction: 'Uzalishaji wa Maziwa wa Kila Siku (Siku 14 Zilizopita)',
    herdStatusDistribution: 'Usambazaji wa Hali ya Kundi',
    monthlyBreedingTrends: 'Mwelekeo wa Uzazi wa Kila Mwezi',
    activityOverview: 'Muhtasari wa Shughuli (Miezi 6 Iliyopita)',
    calvings: 'Kuzaa',
    noDataAvailable: 'Hakuna data inayopatikana',
    noMilkData: 'Hakuna data ya uzalishaji wa maziwa',
    heatDetectionDesc: 'Fuatilia na kufuatilia mizunguko ya joto na data ya sensori',
    breedingCalendarDesc: 'Fuatilia matukio ya uzazi na wakati unaofaa',
    staffAttendanceDesc: 'Fuatilia mahudhurio ya wafanyakazi na uthibitisho wa kibaiolojia',
    healthRecordsTitle: 'Rekodi za Afya',
    addHealthRecord: 'Ongeza Rekodi ya Afya',
    date: 'Tarehe',
    recordType: 'Aina ya Rekodi',
    diagnosis: 'Uchunguzi',
    treatment: 'Matibabu',
    medications: 'Dawa',
    veterinarian: 'Daktari wa Mifugo',
    cost: 'Gharama',
    followUpDate: 'Tarehe ya Ufuatiliaji',
    saveRecord: 'Hifadhi Rekodi',
    noHealthRecords: 'Hakuna rekodi za afya bado',
    failedLoadHealth: 'Imeshindwa kupakia rekodi za afya',
    healthRecordAdded: 'Rekodi ya afya imeongezwa',
    failedAddHealth: 'Imeshindwa kuongeza rekodi ya afya',
    vet: 'Dakt',
    followUp: 'Ufuatiliaji',
    enterDiagnosis: 'Ingiza uchunguzi',
    vetName: 'Jina la daktari',
    describeTreatment: 'Elezea matibabu',
    listMedications: 'Orodhesha dawa',
    additionalNotes: 'Maelezo ya ziada...',
    milkProductionTitle: 'Uzalishaji wa Maziwa',
    recordManualEntry: 'Rekodi Ingizo la Mkono',
    quantityLiters: 'Kiasi (Lita)',
    qualityGrade: 'Daraja la Ubora',
    fatPercentage: 'Mafuta %',
    proteinPercentage: 'Protini %',
    noMilkRecords: 'Hakuna rekodi za uzalishaji wa maziwa bado',
    failedLoadMilk: 'Imeshindwa kupakia rekodi za uzalishaji wa maziwa',
    milkRecordAdded: 'Uzalishaji wa maziwa umeandikwa',
    failedAddMilk: 'Imeshindwa kuongeza rekodi ya uzalishaji wa maziwa',
    avgSession: 'Wast/Kipindi',
    thirtyDayTotalLabel: 'Jumla Siku 30',
    productionTrend: 'Mwelekeo wa Uzalishaji (Rekodi 14 za Mwisho)',
    liters: 'Lita',
    grade: 'Daraja',
    auto: 'Auto',
    newMilkRecorded: 'Uzalishaji mpya wa maziwa umeandikwa na sensori',
    vaccination: 'Chanjo',
    checkup: 'Uchunguzi',
    surgery: 'Upasuaji',
    deworming: 'Kupiga Dawa',
    hoofTrimming: 'Kukata Kwato',
    pregnancyCheck: 'Uchunguzi wa Ujauzito',
    other: 'Nyingine',
  },
  ta: {
    cowManagementDesc: 'நிகழ்நேர சென்சார் புதுப்பிப்புகளுடன் உங்கள் மந்தை தகவல்களை நிர்வகிக்கவும்',
    editCow: 'மாடு திருத்து',
    addNewCow: 'புதிய மாடு சேர்',
    updateCow: 'மாடு புதுப்பி',
    noCowsYet: 'இன்னும் மாடுகள் இல்லை',
    noCowsFound: 'மாடுகள் கிடைக்கவில்லை',
    addFirstCow: 'உங்கள் முதல் மாட்டை சேர்க்கவும்',
    addFirstCowDesc: 'தொடங்க உங்கள் முதல் மாட்டை சேர்க்கவும்',
    tryDifferentSearch: 'வேறு தேடல் சொல்லை முயற்சிக்கவும்',
    searchByNameOrTag: 'பெயர் அல்லது குறி மூலம் தேடு...',
    today: 'இன்று',
    total: 'மொத்தம்',
    latestSensorData: 'சமீபத்திய சென்சார் தரவு',
    sensor: 'சென்சார்',
    reading: 'வாசிப்பு',
    heatIntensity: 'வெப்ப தீவிரம்',
    aiConfidence: 'AI நம்பிக்கை',
    detected: 'கண்டறியப்பட்டது',
    born: 'பிறந்தது',
    milk: 'பால்',
    health: 'ஆரோக்கியம்',
    pregnant: 'கர்ப்பமான',
    sick: 'நோய்வாய்ப்பட்ட',
    analyticsDashboard: 'பகுப்பாய்வு டாஷ்போர்டு',
    analyticsDesc: 'உங்கள் மந்தையின் இனப்பெருக்க செயல்திறன் மற்றும் பால் உற்பத்தியைக் கண்காணிக்கவும்',
    totalCowsLabel: 'மொத்த மாடுகள்',
    heatDetectionsLabel: 'வெப்ப கண்டறிதல்கள்',
    thirtyDayMilk: '30-நாள் பால்',
    avgPerDay: 'சராசரி/நாள்',
    inseminations: 'கருவூட்டல்கள்',
    dailyMilkProduction: 'தினசரி பால் உற்பத்தி (கடந்த 14 நாட்கள்)',
    herdStatusDistribution: 'மந்தை நிலை விநியோகம்',
    monthlyBreedingTrends: 'மாதாந்திர இனப்பெருக்க போக்குகள்',
    activityOverview: 'செயல்பாட்டு மேலோட்டம் (கடந்த 6 மாதங்கள்)',
    calvings: 'கன்று ஈனுதல்',
    noDataAvailable: 'தரவு கிடைக்கவில்லை',
    noMilkData: 'பால் உற்பத்தி தரவு கிடைக்கவில்லை',
    heatDetectionDesc: 'சென்சார் தரவுகளுடன் வெப்ப சுழற்சிகளை கண்காணித்து கண்காணிக்கவும்',
    breedingCalendarDesc: 'இனப்பெருக்க நிகழ்வுகள் மற்றும் சரியான நேரத்தை கண்காணிக்கவும்',
    staffAttendanceDesc: 'பயோமெட்ரிக் சரிபார்ப்புடன் ஊழியர் வருகையை கண்காணிக்கவும்',
    healthRecordsTitle: 'ஆரோக்கிய பதிவுகள்',
    addHealthRecord: 'ஆரோக்கிய பதிவு சேர்',
    date: 'தேதி',
    recordType: 'பதிவு வகை',
    diagnosis: 'நோயறிதல்',
    treatment: 'சிகிச்சை',
    medications: 'மருந்துகள்',
    veterinarian: 'கால்நடை மருத்துவர்',
    cost: 'செலவு',
    followUpDate: 'பின்தொடர்தல் தேதி',
    saveRecord: 'பதிவு சேமி',
    noHealthRecords: 'இன்னும் ஆரோக்கிய பதிவுகள் இல்லை',
    failedLoadHealth: 'ஆரோக்கிய பதிவுகளை ஏற்ற முடியவில்லை',
    healthRecordAdded: 'ஆரோக்கிய பதிவு சேர்க்கப்பட்டது',
    failedAddHealth: 'ஆரோக்கிய பதிவு சேர்க்க முடியவில்லை',
    vet: 'மருத்துவர்',
    followUp: 'பின்தொடர்தல்',
    enterDiagnosis: 'நோயறிதல் உள்ளிடவும்',
    vetName: 'மருத்துவர் பெயர்',
    describeTreatment: 'சிகிச்சையை விவரிக்கவும்',
    listMedications: 'மருந்துகளை பட்டியலிடவும்',
    additionalNotes: 'கூடுதல் குறிப்புகள்...',
    milkProductionTitle: 'பால் உற்பத்தி',
    recordManualEntry: 'கைமுறை பதிவு',
    quantityLiters: 'அளவு (லிட்டர்)',
    qualityGrade: 'தர நிலை',
    fatPercentage: 'கொழுப்பு %',
    proteinPercentage: 'புரதம் %',
    noMilkRecords: 'இன்னும் பால் உற்பத்தி பதிவுகள் இல்லை',
    failedLoadMilk: 'பால் உற்பத்தி பதிவுகளை ஏற்ற முடியவில்லை',
    milkRecordAdded: 'பால் உற்பத்தி பதிவு செய்யப்பட்டது',
    failedAddMilk: 'பால் உற்பத்தி பதிவு சேர்க்க முடியவில்லை',
    avgSession: 'சராசரி/அமர்வு',
    thirtyDayTotalLabel: '30 நாள் மொத்தம்',
    productionTrend: 'உற்பத்தி போக்கு (கடைசி 14 பதிவுகள்)',
    liters: 'லிட்டர்',
    grade: 'தரம்',
    auto: 'தானியங்கி',
    newMilkRecorded: 'சென்சார் மூலம் புதிய பால் உற்பத்தி பதிவு செய்யப்பட்டது',
    vaccination: 'தடுப்பூசி',
    checkup: 'பரிசோதனை',
    surgery: 'அறுவை சிகிச்சை',
    deworming: 'புழு நீக்கம்',
    hoofTrimming: 'குளம்பு வெட்டுதல்',
    pregnancyCheck: 'கர்ப்ப பரிசோதனை',
    other: 'மற்றவை',
  },
  hi: {
    cowManagementDesc: 'रीयल-टाइम सेंसर अपडेट के साथ अपने झुंड की जानकारी प्रबंधित करें',
    editCow: 'गाय संपादित करें',
    addNewCow: 'नई गाय जोड़ें',
    updateCow: 'गाय अपडेट करें',
    noCowsYet: 'अभी तक कोई गाय नहीं',
    noCowsFound: 'कोई गाय नहीं मिली',
    addFirstCow: 'अपनी पहली गाय जोड़ें',
    addFirstCowDesc: 'शुरू करने के लिए अपनी पहली गाय जोड़ें',
    tryDifferentSearch: 'कोई अलग खोज शब्द आज़माएं',
    searchByNameOrTag: 'नाम या टैग से खोजें...',
    today: 'आज',
    total: 'कुल',
    latestSensorData: 'नवीनतम सेंसर डेटा',
    sensor: 'सेंसर',
    reading: 'रीडिंग',
    heatIntensity: 'गर्मी तीव्रता',
    aiConfidence: 'AI विश्वास',
    detected: 'पता चला',
    born: 'जन्म',
    milk: 'दूध',
    health: 'स्वास्थ्य',
    pregnant: 'गर्भवती',
    sick: 'बीमार',
    analyticsDashboard: 'एनालिटिक्स डैशबोर्ड',
    analyticsDesc: 'अपने झुंड के प्रजनन प्रदर्शन और दूध उत्पादन को ट्रैक करें',
    totalCowsLabel: 'कुल गाय',
    heatDetectionsLabel: 'गर्मी पता लगाना',
    thirtyDayMilk: '30-दिन दूध',
    avgPerDay: 'औसत/दिन',
    inseminations: 'कृत्रिम गर्भाधान',
    dailyMilkProduction: 'दैनिक दूध उत्पादन (पिछले 14 दिन)',
    herdStatusDistribution: 'झुंड स्थिति वितरण',
    monthlyBreedingTrends: 'मासिक प्रजनन रुझान',
    activityOverview: 'गतिविधि अवलोकन (पिछले 6 महीने)',
    calvings: 'बछड़े पैदा होना',
    noDataAvailable: 'कोई डेटा उपलब्ध नहीं',
    noMilkData: 'दूध उत्पादन डेटा उपलब्ध नहीं',
    heatDetectionDesc: 'सेंसर डेटा के साथ गर्मी चक्र की निगरानी और ट्रैक करें',
    breedingCalendarDesc: 'प्रजनन कार्यक्रमों और इष्टतम समय को ट्रैक करें',
    staffAttendanceDesc: 'बायोमेट्रिक सत्यापन के साथ कर्मचारी उपस्थिति ट्रैक करें',
    healthRecordsTitle: 'स्वास्थ्य रिकॉर्ड',
    addHealthRecord: 'स्वास्थ्य रिकॉर्ड जोड़ें',
    date: 'तारीख',
    recordType: 'रिकॉर्ड प्रकार',
    diagnosis: 'निदान',
    treatment: 'उपचार',
    medications: 'दवाएं',
    veterinarian: 'पशु चिकित्सक',
    cost: 'लागत',
    followUpDate: 'फॉलो-अप तारीख',
    saveRecord: 'रिकॉर्ड सेव करें',
    noHealthRecords: 'अभी तक कोई स्वास्थ्य रिकॉर्ड नहीं',
    failedLoadHealth: 'स्वास्थ्य रिकॉर्ड लोड करने में विफल',
    healthRecordAdded: 'स्वास्थ्य रिकॉर्ड जोड़ा गया',
    failedAddHealth: 'स्वास्थ्य रिकॉर्ड जोड़ने में विफल',
    vet: 'डॉक्टर',
    followUp: 'फॉलो-अप',
    enterDiagnosis: 'निदान दर्ज करें',
    vetName: 'डॉक्टर का नाम',
    describeTreatment: 'उपचार का वर्णन करें',
    listMedications: 'दवाओं की सूची',
    additionalNotes: 'अतिरिक्त नोट्स...',
    milkProductionTitle: 'दूध उत्पादन',
    recordManualEntry: 'मैनुअल प्रविष्टि दर्ज करें',
    quantityLiters: 'मात्रा (लीटर)',
    qualityGrade: 'गुणवत्ता ग्रेड',
    fatPercentage: 'वसा %',
    proteinPercentage: 'प्रोटीन %',
    noMilkRecords: 'अभी तक कोई दूध उत्पादन रिकॉर्ड नहीं',
    failedLoadMilk: 'दूध उत्पादन रिकॉर्ड लोड करने में विफल',
    milkRecordAdded: 'दूध उत्पादन दर्ज किया गया',
    failedAddMilk: 'दूध उत्पादन रिकॉर्ड जोड़ने में विफल',
    avgSession: 'औसत/सत्र',
    thirtyDayTotalLabel: '30 दिन कुल',
    productionTrend: 'उत्पादन प्रवृत्ति (पिछले 14 रिकॉर्ड)',
    liters: 'लीटर',
    grade: 'ग्रेड',
    auto: 'ऑटो',
    newMilkRecorded: 'सेंसर द्वारा नया दूध उत्पादन दर्ज',
    vaccination: 'टीकाकरण',
    checkup: 'जांच',
    surgery: 'सर्जरी',
    deworming: 'कृमिनाशक',
    hoofTrimming: 'खुर की छंटाई',
    pregnancyCheck: 'गर्भावस्था जांच',
    other: 'अन्य',
  },
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    settings: 'Settings',
    totalCows: 'Total Cows',
    healthy: 'Healthy',
    inHeat: 'In Heat',
    heatDetections: 'Heat Detections (7d)',
    absentStaff: 'Absent Staff',
    noAbsentStaff: 'All staff present today',
    quickTips: 'Quick Tips',
    gettingStarted: 'Getting Started',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    toggleDarkTheme: 'Toggle dark theme',
    profile: 'Profile',
    editProfile: 'Edit Profile',
    fullName: 'Full Name',
    farmName: 'Farm Name',
    farmLocation: 'Farm Location',
    saveChanges: 'Save Changes',
    language: 'Language',
    selectLanguage: 'Select your preferred language',
    english: 'English',
    spanish: 'Spanish',
    french: 'French',
    swahili: 'Swahili',
    tamil: 'Tamil',
    hindi: 'Hindi',
    monthlyStock: 'Monthly Stock Items',
    addItem: 'Add Item',
    noStockItems: 'No stock items for this month',
    itemAdded: 'Item added',
    itemUpdated: 'Item updated',
    itemDeleted: 'Item deleted',
    // Navigation
    cowManagement: 'Cow Management',
    heatDetection: 'Heat Detection',
    breedingCalendar: 'Breeding Calendar',
    staffAttendance: 'Staff Attendance',
    analytics: 'Analytics',
    aiAssistant: 'AI Assistant',
    signOut: 'Sign Out',
    signOutConfirmation: 'Are you sure you want to sign out? You will need to sign in again to access your farm data.',
    // AI Chat
    askAnything: 'Ask anything about cattle breeding',
    howCanIHelp: 'How can I help?',
    askAboutBreeding: 'Ask about breeding, heat detection, or herd health.',
    typeMessage: 'Type your message...',
    send: 'Send',
    uploadImage: 'Upload Image',
    recordAudio: 'Record Audio',
    stopRecording: 'Stop Recording',
    processing: 'Processing...',
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    save: 'Save',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    // Cow Management
    cowManagementDesc: 'Manage your herd information with real-time sensor updates',
    addCow: 'Add Cow',
    cowName: 'Cow Name',
    tagNumber: 'Tag Number',
    breed: 'Breed',
    dateOfBirth: 'Date of Birth',
    weight: 'Weight',
    status: 'Status',
    notes: 'Notes',
    healthRecords: 'Health Records',
    milkProduction: 'Milk Production',
    editCow: 'Edit Cow',
    addNewCow: 'Add New Cow',
    updateCow: 'Update Cow',
    noCowsYet: 'No cows yet',
    noCowsFound: 'No cows found',
    addFirstCow: 'Add Your First Cow',
    addFirstCowDesc: 'Add your first cow to get started',
    tryDifferentSearch: 'Try a different search term',
    searchByNameOrTag: 'Search by name or tag...',
    today: 'Today',
    total: 'Total',
    latestSensorData: 'Latest Sensor Data',
    sensor: 'Sensor',
    reading: 'Reading',
    heatIntensity: 'Heat Intensity',
    aiConfidence: 'AI Confidence',
    detected: 'Detected',
    born: 'Born',
    milk: 'Milk',
    health: 'Health',
    // Heat Detection
    currentlyInHeat: 'Currently in Heat',
    predictedHeat: 'Predicted Heat',
    lastHeatDate: 'Last Heat Date',
    cycleLength: 'Cycle Length',
    // Breeding
    upcomingEvents: 'Upcoming Events',
    pastEvents: 'Past Events',
    addEvent: 'Add Event',
    eventType: 'Event Type',
    eventDate: 'Event Date',
    // Staff
    staffMembers: 'Staff Members',
    addStaff: 'Add Staff',
    staffName: 'Staff Name',
    role: 'Role',
    phone: 'Phone',
    present: 'Present',
    absent: 'Absent',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    // Sensor Dashboard
    sensorDashboard: 'Sensor Dashboard',
    lastUpdated: 'Last updated',
    online: 'Online',
    warning: 'Warning',
    offline: 'Offline',
    readings: 'readings',
    lastReading: 'Last reading',
    time: 'Time',
    noDataReceived: 'No data received yet',
    activitySensor: 'Activity Sensor',
    temperatureSensor: 'Temperature Sensor',
    weightSensor: 'Weight Sensor',
    milkSensor: 'Milk Sensor',
    pedometerSensor: 'Pedometer',
    neckCollarSensor: 'Neck Collar',
    earTagSensor: 'Ear Tag Sensor',
    vaginalTempSensor: 'Vaginal Temp Sensor',
    rumenBolusSensor: 'Rumen Bolus',
    mountingSensor: 'Mounting Sensor',
    tailHeadSensor: 'Tail Head Sensor',
    ruminationSensor: 'Rumination Sensor',
    progesteroneSensor: 'Progesterone Sensor',
    // Voice features
    playVoice: 'Play voice response',
    stopVoice: 'Stop voice',
    voiceEnabled: 'Voice responses enabled',
    voiceDisabled: 'Voice responses disabled',
    transcribing: 'Transcribing...',
    // Auth translations
    authTagline: 'Smart Breeding Platform',
    authWelcomeBackTitle: 'Welcome back',
    authCreateAccountTitle: 'Create account',
    authResetPasswordTitle: 'Reset password',
    authLoginSubtitle: 'Sign in to access your farm dashboard',
    authSignupSubtitle: 'Join to start managing your herd',
    authResetPasswordSubtitle: 'Enter your email to receive a reset link',
    authFullName: 'Full Name',
    authFullNamePlaceholder: 'Enter your full name',
    authEmail: 'Email',
    authEmailPlaceholder: 'Enter your email',
    authPassword: 'Password',
    authPasswordPlaceholder: 'Enter your password',
    authForgotPassword: 'Forgot password?',
    authSignIn: 'Sign In',
    authSignUp: 'Sign Up',
    authCreateAccountBtn: 'Create Account',
    authSending: 'Sending...',
    authSigningIn: 'Signing in...',
    authCreatingAccount: 'Creating account...',
    authSendResetLink: 'Send Reset Link',
    authBackToSignIn: 'Back to Sign In',
    authNoAccount: "Don't have an account?",
    authHaveAccount: 'Already have an account?',
    // Getting Started
    gsWelcome: 'Welcome to Breeding App!',
    gsSteps: 'Start by adding your first cow or staff member.',
    gsAddCow: 'Add Cow',
    gsAddStaff: 'Add Staff',
    gsConfigureSettings: 'Configure your farm settings',
    // App name
    appName: 'AI-FARM APP',
    // Settings
    settingsDesc: 'Manage your preferences',
    pushNotifications: 'Push Notifications',
    enableNotifications: 'Enable Notifications',
    notificationsSupportedDesc: 'Get alerts for heat detection, sensor updates',
    notificationsNotSupported: 'Not supported in this browser',
    // Staff Attendance
    presentNow: 'Present Now',
    checkedOut: 'Checked Out',
    notCheckedIn: 'Not Checked In',
    totalStaff: 'Total Staff',
    todayAttendance: "Today's Attendance",
    // Calendar / Breeding
    heatDetected: 'Heat Detected',
    insemination: 'Insemination',
    pregnancyCheckEvent: 'Pregnancy Check',
    expectedCalving: 'Expected Calving',
    actualCalving: 'Actual Calving',
    selectADate: 'Select a date',
    optimalBreedingWindow: 'Optimal Breeding Window',
    scheduledEvents: 'Scheduled Events',
    noEventsOnDate: 'No events on this date',
    addBreedingEvent: 'Add Breeding Event',
    selectCow: 'Select Cow',
    chooseCow: 'Choose a cow',
    title: 'Title',
    optional: 'optional',
    description: 'Description',
    autoGeneratedIfEmpty: 'Auto-generated if empty',
    adding: 'Adding...',
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    adminDashboardDesc: 'Manage all users, cows, and farm data',
    totalUsers: 'Total Users',
    registeredUsers: 'Registered users',
    acrossAllFarms: 'Across all farms',
    todayMilk: "Today's Milk",
    totalProduction: 'Total production',
    activeLocations: 'Active Locations',
    farmLocations: 'Farm locations',
    users: 'Users',
    allUsers: 'All Users',
    allUsersDesc: 'View all registered users and their farm details',
    allCows: 'All Cows',
    allCowsDesc: 'View all cows across all farms',
    allMilkProduction: 'All Milk Production',
    allMilkProductionDesc: 'Recent milk production records from all farms',
    adminName: 'Name',
    adminFarmName: 'Farm Name',
    adminLocation: 'Location',
    joinedDate: 'Joined Date',
    notSet: 'Not set',
    noUsersFound: 'No users found',
    adminCowName: 'Cow Name',
    adminTagNumber: 'Tag Number',
    adminBreed: 'Breed',
    owner: 'Owner',
    addedDate: 'Added Date',
    unknown: 'Unknown',
    adminQuantity: 'Quantity',
    recordedAt: 'Recorded At',
    noMilkRecordsFound: 'No milk records found',
    admin: 'Admin',
  },
  es: {
    dashboard: 'Panel',
    dashboardWelcome: '¡Bienvenido de nuevo! Aquí está el resumen de tu granja.',
    addRecommendedItems: 'Agregar artículos recomendados',
    enterItemName: 'Ingrese el nombre del artículo...',
    tipOptimalBreedingTitle: 'Tiempo Óptimo de Reproducción',
    tipOptimalBreedingBody: 'Los mejores resultados se logran 12-18 horas después de detectar el celo. Usa nuestra IA para seguir los ciclos.',
    tipAiAssistantTitle: 'Asistente IA Listo',
    tipAiAssistantBody: 'Pregunta a nuestro chatbot de IA sobre reproducción, salud o manejo del rebaño.',
    gsAddFirstCow: 'Agrega tu primera vaca al sistema',
    gsRecordHeat: 'Registra un evento de detección de celo',
    gsAskAi: 'Pide consejo de reproducción a la IA',
    gsConfigureSettings: 'Configura los ajustes de tu granja',
    authTagline: 'Plataforma de Reproducción Inteligente',
    authWelcomeBackTitle: 'Bienvenido de nuevo',
    authCreateAccountTitle: 'Crear cuenta',
    authResetPasswordTitle: 'Restablecer contraseña',
    authLoginSubtitle: 'Inicia sesión para acceder a tu panel de granja',
    authSignupSubtitle: 'Empieza con reproducción impulsada por IA',
    authResetPasswordSubtitle: 'Ingresa tu correo para recibir un enlace de restablecimiento',
    authFullName: 'Nombre completo',
    authFullNamePlaceholder: 'Juan Agricultor',
    authEmail: 'Correo',
    authEmailPlaceholder: 'tu@granja.com',
    authPassword: 'Contraseña',
    authPasswordPlaceholder: '••••••••',
    authForgotPassword: '¿Olvidaste tu contraseña?',
    authSending: 'Enviando...',
    authSigningIn: 'Iniciando sesión...',
    authCreatingAccount: 'Creando cuenta...',
    authSendResetLink: 'Enviar enlace',
    authSignIn: 'Iniciar sesión',
    authSignUp: 'Registrarse',
    authCreateAccountBtn: 'Crear cuenta',
    authBackToSignIn: '← Volver a iniciar sesión',
    authNoAccount: '¿No tienes cuenta?',
    authHaveAccount: '¿Ya tienes cuenta?',
    settings: 'Configuración',

    noAbsentStaff: 'Todo el personal presente hoy',
    quickTips: 'Consejos Rápidos',
    gettingStarted: 'Comenzar',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    toggleDarkTheme: 'Alternar tema oscuro',
    profile: 'Perfil',
    editProfile: 'Editar Perfil',
    fullName: 'Nombre Completo',
    farmName: 'Nombre de la Granja',
    farmLocation: 'Ubicación de la Granja',
    saveChanges: 'Guardar Cambios',
    language: 'Idioma',
    selectLanguage: 'Seleccione su idioma preferido',
    english: 'Inglés',
    spanish: 'Español',
    french: 'Francés',
    swahili: 'Suajili',
    tamil: 'Tamil',
    hindi: 'Hindi',
    monthlyStock: 'Artículos de Stock Mensual',
    addItem: 'Agregar Artículo',
    noStockItems: 'Sin artículos de stock este mes',
    itemAdded: 'Artículo agregado',
    itemUpdated: 'Artículo actualizado',
    itemDeleted: 'Artículo eliminado',
    cowManagement: 'Gestión de Vacas',
    heatDetection: 'Detección de Celo',
    breedingCalendar: 'Calendario de Cría',
    staffAttendance: 'Asistencia del Personal',
    analytics: 'Análisis',
    aiAssistant: 'Asistente IA',
    signOut: 'Cerrar Sesión',
    signOutConfirmation: '¿Está seguro de que desea cerrar sesión? Necesitará iniciar sesión de nuevo para acceder a los datos de su granja.',
    askAnything: 'Pregunte sobre cría de ganado',
    howCanIHelp: '¿Cómo puedo ayudar?',
    askAboutBreeding: 'Pregunte sobre cría, detección de celo o salud del rebaño.',
    typeMessage: 'Escriba su mensaje...',
    send: 'Enviar',
    uploadImage: 'Subir Imagen',
    recordAudio: 'Grabar Audio',
    stopRecording: 'Detener Grabación',
    processing: 'Procesando...',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    save: 'Guardar',
    close: 'Cerrar',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    refresh: 'Actualizar',
    addCow: 'Agregar Vaca',
    cowName: 'Nombre de la Vaca',
    tagNumber: 'Número de Etiqueta',
    breed: 'Raza',
    dateOfBirth: 'Fecha de Nacimiento',
    weight: 'Peso',
    status: 'Estado',
    notes: 'Notas',
    healthRecords: 'Registros de Salud',
    milkProduction: 'Producción de Leche',
    currentlyInHeat: 'Actualmente en Celo',
    predictedHeat: 'Celo Predicho',
    lastHeatDate: 'Última Fecha de Celo',
    cycleLength: 'Duración del Ciclo',
    upcomingEvents: 'Próximos Eventos',
    pastEvents: 'Eventos Pasados',
    addEvent: 'Agregar Evento',
    eventType: 'Tipo de Evento',
    eventDate: 'Fecha del Evento',
    staffMembers: 'Miembros del Personal',
    addStaff: 'Agregar Personal',
    staffName: 'Nombre del Personal',
    role: 'Rol',
    phone: 'Teléfono',
    present: 'Presente',
    absent: 'Ausente',
    checkIn: 'Registrar Entrada',
    checkOut: 'Registrar Salida',
    // Sensor Dashboard
    sensorDashboard: 'Panel de Sensores',
    lastUpdated: 'Última actualización',
    online: 'En línea',
    warning: 'Advertencia',
    offline: 'Desconectado',
    readings: 'lecturas',
    lastReading: 'Última lectura',
    time: 'Hora',
    noDataReceived: 'Sin datos recibidos',
    activitySensor: 'Sensor de Actividad',
    temperatureSensor: 'Sensor de Temperatura',
    weightSensor: 'Sensor de Peso',
    milkSensor: 'Sensor de Leche',
    pedometerSensor: 'Podómetro',
    neckCollarSensor: 'Collar de Cuello',
    earTagSensor: 'Etiqueta de Oreja',
    vaginalTempSensor: 'Sensor Temp. Vaginal',
    rumenBolusSensor: 'Bolo Ruminal',
    mountingSensor: 'Sensor de Monta',
    tailHeadSensor: 'Sensor de Cola',
    ruminationSensor: 'Sensor de Rumia',
    progesteroneSensor: 'Sensor de Progesterona',
    playVoice: 'Reproducir voz',
    stopVoice: 'Detener voz',
    voiceEnabled: 'Voz habilitada',
    voiceDisabled: 'Voz deshabilitada',
    transcribing: 'Transcribiendo...',
    // App name
    appName: 'AI-FARM APP',
    // Settings
    settingsDesc: 'Administra tus preferencias',
    pushNotifications: 'Notificaciones Push',
    enableNotifications: 'Habilitar Notificaciones',
    notificationsSupportedDesc: 'Recibe alertas de detección de celo, actualizaciones de sensores',
    notificationsNotSupported: 'No compatible con este navegador',
    // Staff Attendance
    presentNow: 'Presente Ahora',
    checkedOut: 'Salió',
    notCheckedIn: 'No Registrado',
    totalStaff: 'Personal Total',
    todayAttendance: 'Asistencia de Hoy',
    // Calendar / Breeding
    heatDetected: 'Celo Detectado',
    insemination: 'Inseminación',
    pregnancyCheckEvent: 'Chequeo de Preñez',
    expectedCalving: 'Parto Esperado',
    actualCalving: 'Parto Real',
    selectADate: 'Selecciona una fecha',
    optimalBreedingWindow: 'Ventana de Reproducción Óptima',
    scheduledEvents: 'Eventos Programados',
    noEventsOnDate: 'Sin eventos en esta fecha',
    addBreedingEvent: 'Agregar Evento de Cría',
    selectCow: 'Seleccionar Vaca',
    chooseCow: 'Elige una vaca',
    title: 'Título',
    optional: 'opcional',
    description: 'Descripción',
    autoGeneratedIfEmpty: 'Autogenerado si está vacío',
    adding: 'Agregando...',
    // Admin Dashboard
    adminDashboard: 'Panel de Administrador',
    adminDashboardDesc: 'Gestionar todos los usuarios, vacas y datos de granja',
    totalUsers: 'Usuarios Totales',
    registeredUsers: 'Usuarios registrados',
    acrossAllFarms: 'En todas las granjas',
    todayMilk: 'Leche de Hoy',
    totalProduction: 'Producción total',
    activeLocations: 'Ubicaciones Activas',
    farmLocations: 'Ubicaciones de granjas',
    users: 'Usuarios',
    allUsers: 'Todos los Usuarios',
    allUsersDesc: 'Ver todos los usuarios registrados y sus detalles de granja',
    allCows: 'Todas las Vacas',
    allCowsDesc: 'Ver todas las vacas en todas las granjas',
    allMilkProduction: 'Toda la Producción de Leche',
    allMilkProductionDesc: 'Registros recientes de producción de leche de todas las granjas',
    adminName: 'Nombre',
    adminFarmName: 'Nombre de Granja',
    adminLocation: 'Ubicación',
    joinedDate: 'Fecha de Registro',
    notSet: 'No establecido',
    noUsersFound: 'No se encontraron usuarios',
    adminCowName: 'Nombre de Vaca',
    adminTagNumber: 'Número de Etiqueta',
    adminBreed: 'Raza',
    owner: 'Propietario',
    addedDate: 'Fecha de Adición',
    unknown: 'Desconocido',
    adminQuantity: 'Cantidad',
    recordedAt: 'Registrado En',
    noMilkRecordsFound: 'No se encontraron registros de leche',
    admin: 'Administrador',
  },
  fr: {
    dashboard: 'Tableau de bord',
    dashboardWelcome: 'Bon retour ! Voici un aperçu de votre ferme.',
    addRecommendedItems: 'Ajouter des articles recommandés',
    enterItemName: "Saisissez le nom de l'article...",
    tipOptimalBreedingTitle: 'Moment de Reproduction Optimal',
    tipOptimalBreedingBody: 'Les meilleurs résultats sont obtenus 12 à 18 heures après la détection de chaleur. Utilisez notre IA pour suivre les cycles.',
    tipAiAssistantTitle: 'Assistant IA Prêt',
    tipAiAssistantBody: 'Posez à notre chatbot IA des questions sur la reproduction, la santé ou la gestion du troupeau.',
    gsAddFirstCow: 'Ajoutez votre première vache au système',
    gsRecordHeat: 'Enregistrez un événement de détection de chaleur',
    gsAskAi: 'Demandez des conseils de reproduction à l’IA',
    gsConfigureSettings: 'Configurez les paramètres de votre ferme',
    authTagline: 'Plateforme de Reproduction Intelligente',
    authWelcomeBackTitle: 'Bon retour',
    authCreateAccountTitle: 'Créer un compte',
    authResetPasswordTitle: 'Réinitialiser le mot de passe',
    authLoginSubtitle: 'Connectez-vous pour accéder à votre tableau de bord',
    authSignupSubtitle: 'Commencez avec la reproduction assistée par IA',
    authResetPasswordSubtitle: 'Saisissez votre email pour recevoir un lien de réinitialisation',
    authFullName: 'Nom complet',
    authFullNamePlaceholder: 'Jean Éleveur',
    authEmail: 'Email',
    authEmailPlaceholder: 'vous@ferme.com',
    authPassword: 'Mot de passe',
    authPasswordPlaceholder: '••••••••',
    authForgotPassword: 'Mot de passe oublié ?',
    authSending: 'Envoi...',
    authSigningIn: 'Connexion...',
    authCreatingAccount: 'Création du compte...',
    authSendResetLink: 'Envoyer le lien',
    authSignIn: 'Se connecter',
    authSignUp: "S'inscrire",
    authCreateAccountBtn: 'Créer un compte',
    authBackToSignIn: '← Retour à la connexion',
    authNoAccount: "Pas de compte ?",
    authHaveAccount: 'Déjà un compte ?',
    settings: 'Paramètres',

    noAbsentStaff: 'Tout le personnel présent',
    quickTips: 'Conseils Rapides',
    gettingStarted: 'Commencer',
    appearance: 'Apparence',
    darkMode: 'Mode Sombre',
    toggleDarkTheme: 'Basculer le thème sombre',
    profile: 'Profil',
    editProfile: 'Modifier le Profil',
    fullName: 'Nom Complet',
    farmName: 'Nom de la Ferme',
    farmLocation: 'Emplacement de la Ferme',
    saveChanges: 'Enregistrer',
    language: 'Langue',
    selectLanguage: 'Sélectionnez votre langue préférée',
    english: 'Anglais',
    spanish: 'Espagnol',
    french: 'Français',
    swahili: 'Swahili',
    tamil: 'Tamoul',
    hindi: 'Hindi',
    monthlyStock: 'Articles de Stock Mensuel',
    addItem: 'Ajouter un Article',
    noStockItems: 'Aucun article de stock ce mois',
    itemAdded: 'Article ajouté',
    itemUpdated: 'Article mis à jour',
    itemDeleted: 'Article supprimé',
    cowManagement: 'Gestion des Vaches',
    heatDetection: 'Détection de Chaleur',
    breedingCalendar: 'Calendrier de Reproduction',
    staffAttendance: 'Présence du Personnel',
    analytics: 'Analyses',
    aiAssistant: 'Assistant IA',
    signOut: 'Déconnexion',
    signOutConfirmation: 'Êtes-vous sûr de vouloir vous déconnecter? Vous devrez vous reconnecter pour accéder aux données de votre ferme.',
    askAnything: 'Posez des questions sur l\'élevage bovin',
    howCanIHelp: 'Comment puis-je aider?',
    askAboutBreeding: 'Posez des questions sur l\'élevage, la détection de chaleur ou la santé du troupeau.',
    typeMessage: 'Tapez votre message...',
    send: 'Envoyer',
    uploadImage: 'Télécharger une Image',
    recordAudio: 'Enregistrer Audio',
    stopRecording: 'Arrêter l\'Enregistrement',
    processing: 'Traitement...',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    save: 'Enregistrer',
    close: 'Fermer',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    import: 'Importer',
    refresh: 'Actualiser',
    addCow: 'Ajouter une Vache',
    cowName: 'Nom de la Vache',
    tagNumber: 'Numéro d\'Étiquette',
    breed: 'Race',
    dateOfBirth: 'Date de Naissance',
    weight: 'Poids',
    status: 'Statut',
    notes: 'Notes',
    healthRecords: 'Dossiers de Santé',
    milkProduction: 'Production Laitière',
    currentlyInHeat: 'Actuellement en Chaleur',
    predictedHeat: 'Chaleur Prédite',
    lastHeatDate: 'Dernière Date de Chaleur',
    cycleLength: 'Durée du Cycle',
    upcomingEvents: 'Événements à Venir',
    pastEvents: 'Événements Passés',
    addEvent: 'Ajouter un Événement',
    eventType: 'Type d\'Événement',
    eventDate: 'Date de l\'Événement',
    staffMembers: 'Membres du Personnel',
    addStaff: 'Ajouter du Personnel',
    staffName: 'Nom du Personnel',
    role: 'Rôle',
    phone: 'Téléphone',
    present: 'Présent',
    absent: 'Absent',
    checkIn: 'Pointer l\'Entrée',
    checkOut: 'Pointer la Sortie',
    // Sensor Dashboard
    sensorDashboard: 'Tableau de Bord des Capteurs',
    lastUpdated: 'Dernière mise à jour',
    online: 'En ligne',
    warning: 'Avertissement',
    offline: 'Hors ligne',
    readings: 'lectures',
    lastReading: 'Dernière lecture',
    time: 'Heure',
    noDataReceived: 'Aucune donnée reçue',
    activitySensor: 'Capteur d\'Activité',
    temperatureSensor: 'Capteur de Température',
    weightSensor: 'Capteur de Poids',
    milkSensor: 'Capteur de Lait',
    pedometerSensor: 'Podomètre',
    neckCollarSensor: 'Collier de Cou',
    earTagSensor: 'Étiquette d\'Oreille',
    vaginalTempSensor: 'Capteur Temp. Vaginale',
    rumenBolusSensor: 'Bolus Ruminal',
    mountingSensor: 'Capteur de Monte',
    tailHeadSensor: 'Capteur de Queue',
    ruminationSensor: 'Capteur de Rumination',
    progesteroneSensor: 'Capteur de Progestérone',
    playVoice: 'Lire la voix',
    stopVoice: 'Arrêter la voix',
    voiceEnabled: 'Voix activée',
    voiceDisabled: 'Voix désactivée',
    transcribing: 'Transcription...',
    // App name
    appName: 'AI-FARM APP',
    // Settings
    settingsDesc: 'Gérer vos préférences',
    pushNotifications: 'Notifications Push',
    enableNotifications: 'Activer les Notifications',
    notificationsSupportedDesc: 'Recevez des alertes pour la détection de chaleur, mises à jour des capteurs',
    notificationsNotSupported: 'Non pris en charge dans ce navigateur',
    // Staff Attendance
    presentNow: 'Présent Maintenant',
    checkedOut: 'Sorti',
    notCheckedIn: 'Non Enregistré',
    totalStaff: 'Personnel Total',
    todayAttendance: "Présence d'Aujourd'hui",
    // Calendar / Breeding
    heatDetected: 'Chaleur Détectée',
    insemination: 'Insémination',
    pregnancyCheckEvent: 'Contrôle de Gestation',
    expectedCalving: 'Vêlage Prévu',
    actualCalving: 'Vêlage Réel',
    selectADate: 'Sélectionnez une date',
    optimalBreedingWindow: 'Fenêtre de Reproduction Optimale',
    scheduledEvents: 'Événements Programmés',
    noEventsOnDate: 'Aucun événement à cette date',
    addBreedingEvent: 'Ajouter un Événement de Reproduction',
    selectCow: 'Sélectionner une Vache',
    chooseCow: 'Choisissez une vache',
    title: 'Titre',
    optional: 'optionnel',
    description: 'Description',
    autoGeneratedIfEmpty: 'Généré automatiquement si vide',
    adding: 'Ajout...',
    // Admin Dashboard
    adminDashboard: 'Tableau de Bord Admin',
    adminDashboardDesc: 'Gérer tous les utilisateurs, vaches et données de ferme',
    totalUsers: 'Utilisateurs Totaux',
    registeredUsers: 'Utilisateurs enregistrés',
    acrossAllFarms: 'Dans toutes les fermes',
    todayMilk: 'Lait Aujourd\'hui',
    totalProduction: 'Production totale',
    activeLocations: 'Emplacements Actifs',
    farmLocations: 'Emplacements de fermes',
    users: 'Utilisateurs',
    allUsers: 'Tous les Utilisateurs',
    allUsersDesc: 'Voir tous les utilisateurs enregistrés et leurs détails de ferme',
    allCows: 'Toutes les Vaches',
    allCowsDesc: 'Voir toutes les vaches dans toutes les fermes',
    allMilkProduction: 'Toute la Production Laitière',
    allMilkProductionDesc: 'Registres récents de production laitière de toutes les fermes',
    adminName: 'Nom',
    adminFarmName: 'Nom de Ferme',
    adminLocation: 'Emplacement',
    joinedDate: 'Date d\'Inscription',
    notSet: 'Non défini',
    noUsersFound: 'Aucun utilisateur trouvé',
    adminCowName: 'Nom de Vache',
    adminTagNumber: 'Numéro d\'Étiquette',
    adminBreed: 'Race',
    owner: 'Propriétaire',
    addedDate: 'Date d\'Ajout',
    unknown: 'Inconnu',
    adminQuantity: 'Quantité',
    recordedAt: 'Enregistré Le',
    noMilkRecordsFound: 'Aucun registre de lait trouvé',
    admin: 'Admin',
  },
  sw: {
    dashboard: 'Dashibodi',
    settings: 'Mipangilio',
    totalCows: 'Jumla ya Ng\'ombe',
    healthy: 'Wenye Afya',
    inHeat: 'Katika Joto',
    heatDetections: 'Ugunduzi wa Joto (7d)',
    absentStaff: 'Wafanyakazi Wasiokuwepo',
    noAbsentStaff: 'Wafanyakazi wote wako leo',
    quickTips: 'Vidokezo vya Haraka',
    gettingStarted: 'Kuanza',
    appearance: 'Muonekano',
    darkMode: 'Hali ya Giza',
    toggleDarkTheme: 'Badilisha mandhari ya giza',
    profile: 'Wasifu',
    editProfile: 'Hariri Wasifu',
    fullName: 'Jina Kamili',
    farmName: 'Jina la Shamba',
    farmLocation: 'Mahali pa Shamba',
    saveChanges: 'Hifadhi Mabadiliko',
    language: 'Lugha',
    selectLanguage: 'Chagua lugha unayopendelea',
    english: 'Kiingereza',
    spanish: 'Kihispania',
    french: 'Kifaransa',
    swahili: 'Kiswahili',
    tamil: 'Kitamil',
    hindi: 'Kihindi',
    monthlyStock: 'Vitu vya Hifadhi vya Mwezi',
    addItem: 'Ongeza Kitu',
    noStockItems: 'Hakuna vitu vya hifadhi mwezi huu',
    itemAdded: 'Kitu kimeongezwa',
    itemUpdated: 'Kitu kimesasishwa',
    itemDeleted: 'Kitu kimefutwa',
    cowManagement: 'Usimamizi wa Ng\'ombe',
    heatDetection: 'Ugunduzi wa Joto',
    breedingCalendar: 'Kalenda ya Uzazi',
    staffAttendance: 'Mahudhurio ya Wafanyakazi',
    analytics: 'Uchambuzi',
    aiAssistant: 'Msaidizi wa AI',
    signOut: 'Ondoka',
    signOutConfirmation: 'Je, una uhakika unataka kuondoka? Utahitaji kuingia tena ili kufikia data ya shamba lako.',
    askAnything: 'Uliza chochote kuhusu ufugaji ng\'ombe',
    howCanIHelp: 'Nawezaje kusaidia?',
    askAboutBreeding: 'Uliza kuhusu uzazi, ugunduzi wa joto, au afya ya kundi.',
    typeMessage: 'Andika ujumbe wako...',
    send: 'Tuma',
    uploadImage: 'Pakia Picha',
    recordAudio: 'Rekodi Sauti',
    stopRecording: 'Simamisha Kurekodi',
    processing: 'Inachakata...',
    loading: 'Inapakia...',
    error: 'Hitilafu',
    success: 'Mafanikio',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    add: 'Ongeza',
    save: 'Hifadhi',
    close: 'Funga',
    search: 'Tafuta',
    filter: 'Chuja',
    export: 'Hamisha',
    import: 'Ingiza',
    refresh: 'Onyesha upya',
    addCow: 'Ongeza Ng\'ombe',
    cowName: 'Jina la Ng\'ombe',
    tagNumber: 'Nambari ya Lebo',
    breed: 'Aina',
    dateOfBirth: 'Tarehe ya Kuzaliwa',
    weight: 'Uzito',
    status: 'Hali',
    notes: 'Maelezo',
    healthRecords: 'Rekodi za Afya',
    milkProduction: 'Uzalishaji wa Maziwa',
    currentlyInHeat: 'Kwa Sasa Katika Joto',
    predictedHeat: 'Joto Lililotabiriwa',
    lastHeatDate: 'Tarehe ya Joto la Mwisho',
    cycleLength: 'Urefu wa Mzunguko',
    upcomingEvents: 'Matukio Yanayokuja',
    pastEvents: 'Matukio Yaliyopita',
    addEvent: 'Ongeza Tukio',
    eventType: 'Aina ya Tukio',
    eventDate: 'Tarehe ya Tukio',
    staffMembers: 'Wanachama wa Wafanyakazi',
    addStaff: 'Ongeza Mfanyakazi',
    staffName: 'Jina la Mfanyakazi',
    role: 'Jukumu',
    phone: 'Simu',
    present: 'Yupo',
    absent: 'Hayupo',
    checkIn: 'Jisajili Kuingia',
    checkOut: 'Jisajili Kutoka',
    // Sensor Dashboard
    sensorDashboard: 'Dashibodi ya Sensori',
    lastUpdated: 'Iliyosasishwa mwisho',
    online: 'Mtandaoni',
    warning: 'Onyo',
    offline: 'Nje ya mtandao',
    readings: 'usomaji',
    lastReading: 'Usomaji wa mwisho',
    time: 'Wakati',
    noDataReceived: 'Hakuna data iliyopokelewa',
    activitySensor: 'Sensori ya Shughuli',
    temperatureSensor: 'Sensori ya Joto',
    weightSensor: 'Sensori ya Uzito',
    milkSensor: 'Sensori ya Maziwa',
    pedometerSensor: 'Pedometer',
    neckCollarSensor: 'Kola ya Shingo',
    earTagSensor: 'Tiketi ya Sikio',
    vaginalTempSensor: 'Sensori Joto la Uke',
    rumenBolusSensor: 'Bolus ya Tumbo',
    mountingSensor: 'Sensori ya Kupanda',
    tailHeadSensor: 'Sensori ya Mkia',
    ruminationSensor: 'Sensori ya Kucheuza',
    progesteroneSensor: 'Sensori ya Projesteroni',
    playVoice: 'Cheza sauti',
    stopVoice: 'Simamisha sauti',
    voiceEnabled: 'Sauti imewashwa',
    voiceDisabled: 'Sauti imezimwa',
    transcribing: 'Kuandika...',
    // App name
    appName: 'AI-FARM APP',
    // Settings
    settingsDesc: 'Simamia mapendeleo yako',
    pushNotifications: 'Arifa za Push',
    enableNotifications: 'Wezesha Arifa',
    notificationsSupportedDesc: 'Pata arifa za ugunduzi wa joto, sasisho za sensori',
    notificationsNotSupported: 'Haitegemewi katika kivinjari hiki',
    // Staff Attendance
    presentNow: 'Yupo Sasa',
    checkedOut: 'Alitoka',
    notCheckedIn: 'Hakujisajili',
    totalStaff: 'Jumla ya Wafanyakazi',
    todayAttendance: 'Mahudhurio ya Leo',
    // Calendar / Breeding
    heatDetected: 'Joto Liligunduliwa',
    insemination: 'Upandishaji',
    pregnancyCheckEvent: 'Uchunguzi wa Ujauzito',
    expectedCalving: 'Kuzaa Kunatarajiwa',
    actualCalving: 'Kuzaa Halisi',
    selectADate: 'Chagua tarehe',
    optimalBreedingWindow: 'Dirisha Bora la Uzazi',
    scheduledEvents: 'Matukio Yaliyopangwa',
    noEventsOnDate: 'Hakuna matukio tarehe hii',
    addBreedingEvent: 'Ongeza Tukio la Uzazi',
    selectCow: "Chagua Ng'ombe",
    chooseCow: "Chagua ng'ombe",
    title: 'Kichwa',
    optional: 'hiari',
    description: 'Maelezo',
    autoGeneratedIfEmpty: 'Itazalishwa kiotomatiki ikiwa tupu',
    adding: 'Inaongeza...',
    // Admin Dashboard
    adminDashboard: 'Dashibodi ya Msimamizi',
    adminDashboardDesc: 'Simamia watumiaji wote, ng\'ombe, na data ya shamba',
    totalUsers: 'Watumiaji Wote',
    registeredUsers: 'Watumiaji waliosajiliwa',
    acrossAllFarms: 'Katika mashamba yote',
    todayMilk: 'Maziwa ya Leo',
    totalProduction: 'Uzalishaji wote',
    activeLocations: 'Maeneo Yanayofanya Kazi',
    farmLocations: 'Maeneo ya mashamba',
    users: 'Watumiaji',
    allUsers: 'Watumiaji Wote',
    allUsersDesc: 'Tazama watumiaji wote waliosajiliwa na maelezo ya shamba lao',
    allCows: 'Ng\'ombe Wote',
    allCowsDesc: 'Tazama ng\'ombe wote katika mashamba yote',
    allMilkProduction: 'Uzalishaji Wote wa Maziwa',
    allMilkProductionDesc: 'Rekodi za hivi karibuni za uzalishaji wa maziwa kutoka mashamba yote',
    adminName: 'Jina',
    adminFarmName: 'Jina la Shamba',
    adminLocation: 'Eneo',
    joinedDate: 'Tarehe ya Kujiunga',
    notSet: 'Haijawekwa',
    noUsersFound: 'Hakuna watumiaji waliopatikana',
    adminCowName: 'Jina la Ng\'ombe',
    adminTagNumber: 'Namba ya Tiketi',
    adminBreed: 'Kizazi',
    owner: 'Mmiliki',
    addedDate: 'Tarehe ya Kuongeza',
    unknown: 'Haijulikani',
    adminQuantity: 'Kiasi',
    recordedAt: 'Ilirekodishwa Wakati',
    noMilkRecordsFound: 'Hakuna rekodi za maziwa zilizopatikana',
    admin: 'Msimamizi',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    dashboardWelcome: 'மீண்டும் வரவேற்கிறோம்! உங்கள் பண்ணை சுருக்கம் இதோ.',
    addRecommendedItems: 'பரிந்துரைக்கப்பட்ட பொருட்களை சேர்',
    enterItemName: 'பொருள் பெயரை உள்ளிடவும்...',
    tipOptimalBreedingTitle: 'சிறந்த இனப்பெருக்க நேரம்',
    tipOptimalBreedingBody: 'வெப்ப கண்டறிதலுக்கு 12-18 மணி நேரத்திற்குப் பிறகு சிறந்த முடிவுகள் கிடைக்கும். எங்கள் AI மூலம் சுழற்சிகளை கண்காணிக்கவும்.',
    tipAiAssistantTitle: 'AI உதவியாளர் தயாராக உள்ளது',
    tipAiAssistantBody: 'இனப்பெருக்கம், ஆரோக்கியம், மந்தை மேலாண்மை குறித்து எங்கள் AI சாட்பாட்டிடம் கேளுங்கள்.',
    gsAddFirstCow: 'உங்கள் முதல் மாட்டை அமைப்பில் சேர்க்கவும்',
    gsRecordHeat: 'வெப்ப கண்டறிதல் நிகழ்வை பதிவு செய்யவும்',
    gsAskAi: 'AI-யிடம் இனப்பெருக்க ஆலோசனை கேளுங்கள்',
    gsConfigureSettings: 'உங்கள் பண்ணை அமைப்புகளை கட்டமைக்கவும்',
    authTagline: 'ஸ்மார்ட் இனப்பெருக்க தளம்',
    authWelcomeBackTitle: 'மீண்டும் வரவேற்கிறோம்',
    authCreateAccountTitle: 'கணக்கு உருவாக்கு',
    authResetPasswordTitle: 'கடவுச்சொல்லை மீட்டமைக்கவும்',
    authLoginSubtitle: 'உங்கள் பண்ணை டாஷ்போர்டை அணுக உள்நுழையவும்',
    authSignupSubtitle: 'AI இயக்கப்படும் இனப்பெருக்கத்துடன் தொடங்குங்கள்',
    authResetPasswordSubtitle: 'மீட்டமைப்பு இணைப்பைப் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    authFullName: 'முழு பெயர்',
    authFullNamePlaceholder: 'ராஜா விவசாயி',
    authEmail: 'மின்னஞ்சல்',
    authEmailPlaceholder: 'you@farm.com',
    authPassword: 'கடவுச்சொல்',
    authPasswordPlaceholder: '••••••••',
    authForgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    authSending: 'அனுப்புகிறது...',
    authSigningIn: 'உள்நுழைகிறது...',
    authCreatingAccount: 'கணக்கு உருவாக்குகிறது...',
    authSendResetLink: 'மீட்டமைப்பு இணைப்பை அனுப்பு',
    authSignIn: 'உள்நுழை',
    authSignUp: 'பதிவு செய்',
    authCreateAccountBtn: 'கணக்கு உருவாக்கு',
    authBackToSignIn: '← உள்நுழைவுக்கு திரும்பு',
    authNoAccount: 'கணக்கு இல்லையா?',
    authHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    settings: 'அமைப்புகள்',

    noAbsentStaff: 'இன்று அனைத்து ஊழியர்களும் உள்ளனர்',
    quickTips: 'விரைவு குறிப்புகள்',
    gettingStarted: 'தொடங்குதல்',
    appearance: 'தோற்றம்',
    darkMode: 'இருண்ட பயன்முறை',
    toggleDarkTheme: 'இருண்ட தீம் மாற்று',
    profile: 'சுயவிவரம்',
    editProfile: 'சுயவிவரத்தை திருத்து',
    fullName: 'முழு பெயர்',
    farmName: 'பண்ணை பெயர்',
    farmLocation: 'பண்ணை இடம்',
    saveChanges: 'மாற்றங்களை சேமி',
    language: 'மொழி',
    selectLanguage: 'உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்',
    english: 'ஆங்கிலம்',
    spanish: 'ஸ்பானிஷ்',
    french: 'பிரெஞ்சு',
    swahili: 'ஸ்வாஹிலி',
    tamil: 'தமிழ்',
    hindi: 'இந்தி',
    monthlyStock: 'மாதாந்திர இருப்பு பொருட்கள்',
    addItem: 'பொருள் சேர்',
    noStockItems: 'இந்த மாதம் இருப்பு பொருட்கள் இல்லை',
    itemAdded: 'பொருள் சேர்க்கப்பட்டது',
    itemUpdated: 'பொருள் புதுப்பிக்கப்பட்டது',
    itemDeleted: 'பொருள் நீக்கப்பட்டது',
    cowManagement: 'மாடு மேலாண்மை',
    heatDetection: 'வெப்ப கண்டறிதல்',
    breedingCalendar: 'இனப்பெருக்க நாட்காட்டி',
    staffAttendance: 'ஊழியர் வருகை',
    analytics: 'பகுப்பாய்வு',
    aiAssistant: 'AI உதவியாளர்',
    signOut: 'வெளியேறு',
    signOutConfirmation: 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா? உங்கள் பண்ணை தரவை அணுக மீண்டும் உள்நுழைய வேண்டும்.',
    askAnything: 'கால்நடை வளர்ப்பு பற்றி எதையும் கேளுங்கள்',
    howCanIHelp: 'நான் எப்படி உதவ முடியும்?',
    askAboutBreeding: 'இனப்பெருக்கம், வெப்ப கண்டறிதல் அல்லது மந்தை ஆரோக்கியம் பற்றி கேளுங்கள்.',
    typeMessage: 'உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...',
    send: 'அனுப்பு',
    uploadImage: 'படம் பதிவேற்று',
    recordAudio: 'ஒலி பதிவு',
    stopRecording: 'பதிவை நிறுத்து',
    processing: 'செயலாக்கம்...',
    loading: 'ஏற்றுகிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    add: 'சேர்',
    save: 'சேமி',
    close: 'மூடு',
    search: 'தேடு',
    filter: 'வடிகட்டு',
    export: 'ஏற்றுமதி',
    import: 'இறக்குமதி',
    refresh: 'புதுப்பி',
    addCow: 'மாடு சேர்',
    cowName: 'மாடு பெயர்',
    tagNumber: 'குறிச்சொல் எண்',
    breed: 'இனம்',
    dateOfBirth: 'பிறந்த தேதி',
    weight: 'எடை',
    status: 'நிலை',
    notes: 'குறிப்புகள்',
    healthRecords: 'சுகாதார பதிவுகள்',
    milkProduction: 'பால் உற்பத்தி',
    currentlyInHeat: 'தற்போது வெப்பத்தில்',
    predictedHeat: 'கணிக்கப்பட்ட வெப்பம்',
    lastHeatDate: 'கடைசி வெப்ப தேதி',
    cycleLength: 'சுழற்சி நீளம்',
    upcomingEvents: 'வரவிருக்கும் நிகழ்வுகள்',
    pastEvents: 'கடந்த நிகழ்வுகள்',
    addEvent: 'நிகழ்வு சேர்',
    eventType: 'நிகழ்வு வகை',
    eventDate: 'நிகழ்வு தேதி',
    staffMembers: 'ஊழியர்கள்',
    addStaff: 'ஊழியர் சேர்',
    staffName: 'ஊழியர் பெயர்',
    role: 'பங்கு',
    phone: 'தொலைபேசி',
    present: 'இருக்கிறார்',
    absent: 'இல்லை',
    checkIn: 'உள்நுழைவு',
    checkOut: 'வெளியேறுதல்',
    // Sensor Dashboard
    sensorDashboard: 'சென்சார் டாஷ்போர்டு',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    online: 'ஆன்லைன்',
    warning: 'எச்சரிக்கை',
    offline: 'ஆஃப்லைன்',
    readings: 'வாசிப்புகள்',
    lastReading: 'கடைசி வாசிப்பு',
    time: 'நேரம்',
    noDataReceived: 'தரவு பெறப்படவில்லை',
    activitySensor: 'செயல்பாட்டு சென்சார்',
    temperatureSensor: 'வெப்பநிலை சென்சார்',
    weightSensor: 'எடை சென்சார்',
    milkSensor: 'பால் சென்சார்',
    pedometerSensor: 'பெடோமீட்டர்',
    neckCollarSensor: 'கழுத்து பட்டை',
    earTagSensor: 'காது குறி',
    vaginalTempSensor: 'யோனி வெப்ப சென்சார்',
    rumenBolusSensor: 'ருமன் போலஸ்',
    mountingSensor: 'ஏறும் சென்சார்',
    tailHeadSensor: 'வால் தலை சென்சார்',
    ruminationSensor: 'அசை போடும் சென்சார்',
    progesteroneSensor: 'புரோஜெஸ்டிரோன் சென்சார்',
    playVoice: 'குரல் இயக்கு',
    stopVoice: 'குரல் நிறுத்து',
    voiceEnabled: 'குரல் இயக்கப்பட்டது',
    voiceDisabled: 'குரல் முடக்கப்பட்டது',
    transcribing: 'எழுதுகிறது...',
    // App name
    appName: 'AI-FARM APP',
    // Settings
    settingsDesc: 'உங்கள் விருப்பங்களை நிர்வகிக்கவும்',
    pushNotifications: 'புஷ் அறிவிப்புகள்',
    enableNotifications: 'அறிவிப்புகளை இயக்கு',
    notificationsSupportedDesc: 'வெப்ப கண்டறிதல், சென்சார் புதுப்பிப்புகளுக்கு விழிப்பூட்டல்கள் பெறுங்கள்',
    notificationsNotSupported: 'இந்த உலாவியில் ஆதரிக்கப்படவில்லை',
    // Staff Attendance
    presentNow: 'இப்போது உள்ளார்',
    checkedOut: 'வெளியேறினார்',
    notCheckedIn: 'பதிவு செய்யப்படவில்லை',
    totalStaff: 'மொத்த ஊழியர்கள்',
    todayAttendance: 'இன்றைய வருகை',
    // Calendar / Breeding
    heatDetected: 'வெப்பம் கண்டறியப்பட்டது',
    insemination: 'கருவூட்டல்',
    pregnancyCheckEvent: 'கர்ப்ப பரிசோதனை',
    expectedCalving: 'எதிர்பார்க்கப்படும் கன்று ஈனுதல்',
    actualCalving: 'உண்மையான கன்று ஈனுதல்',
    selectADate: 'ஒரு தேதியை தேர்ந்தெடுக்கவும்',
    optimalBreedingWindow: 'சிறந்த இனப்பெருக்க சாளரம்',
    scheduledEvents: 'திட்டமிடப்பட்ட நிகழ்வுகள்',
    noEventsOnDate: 'இந்த தேதியில் நிகழ்வுகள் இல்லை',
    addBreedingEvent: 'இனப்பெருக்க நிகழ்வை சேர்',
    selectCow: 'மாட்டை தேர்வு செய்',
    chooseCow: 'ஒரு மாட்டை தேர்ந்தெடுக்கவும்',
    title: 'தலைப்பு',
    optional: 'விருப்பமான',
    description: 'விளக்கம்',
    autoGeneratedIfEmpty: 'காலியாக இருந்தால் தானாக உருவாக்கப்படும்',
    adding: 'சேர்க்கிறது...',
    // Admin Dashboard
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    adminDashboardDesc: 'அனைத்து பயனர்கள், மாடுகள் மற்றும் பண்ணை தரவை நிர்வகிக்கவும்',
    totalUsers: 'மொத்த பயனர்கள்',
    registeredUsers: 'பதிவு செய்யப்பட்ட பயனர்கள்',
    acrossAllFarms: 'அனைத்து பண்ணைகளிலும்',
    todayMilk: 'இன்றைய பால்',
    totalProduction: 'மொத்த உற்பத்தி',
    activeLocations: 'செயலில் உள்ள இடங்கள்',
    farmLocations: 'பண்ணை இடங்கள்',
    users: 'பயனர்கள்',
    allUsers: 'அனைத்து பயனர்கள்',
    allUsersDesc: 'அனைத்து பதிவு செய்யப்பட்ட பயனர்கள் மற்றும் அவர்களின் பண்ணை விவரங்களைப் பார்க்கவும்',
    allCows: 'அனைத்து மாடுகள்',
    allCowsDesc: 'அனைத்து பண்ணைகளிலும் உள்ள மாடுகளைப் பார்க்கவும்',
    allMilkProduction: 'அனைத்து பால் உற்பத்தி',
    allMilkProductionDesc: 'அனைத்து பண்ணைகளிலிருந்தும் சமீபத்திய பால் உற்பத்தி பதிவுகள்',
    adminName: 'பெயர்',
    adminFarmName: 'பண்ணை பெயர்',
    adminLocation: 'இடம்',
    joinedDate: 'சேர்ந்த தேதி',
    notSet: 'அமைக்கப்படவில்லை',
    noUsersFound: 'பயனர்கள் கிடைக்கவில்லை',
    adminCowName: 'மாட்டின் பெயர்',
    adminTagNumber: 'குறி எண்',
    adminBreed: 'இனம்',
    owner: 'உரிமையாளர்',
    addedDate: 'சேர்க்கப்பட்ட தேதி',
    unknown: 'தெரியாது',
    adminQuantity: 'அளவு',
    recordedAt: 'பதிவு செய்யப்பட்ட நேரம்',
    noMilkRecordsFound: 'பால் பதிவுகள் கிடைக்கவில்லை',
    admin: 'நிர்வாகி',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    dashboardWelcome: 'वापस स्वागत है! यह रहा आपके फार्म का सारांश।',
    addRecommendedItems: 'अनुशंसित आइटम जोड़ें',
    enterItemName: 'आइटम का नाम लिखें...',
    tipOptimalBreedingTitle: 'उत्तम प्रजनन समय',
    tipOptimalBreedingBody: 'गर्मी का पता चलने के 12-18 घंटे बाद सर्वोत्तम परिणाम मिलते हैं। चक्र ट्रैक करने के लिए AI का उपयोग करें।',
    tipAiAssistantTitle: 'AI सहायक तैयार',
    tipAiAssistantBody: 'प्रजनन, स्वास्थ्य या झुंड प्रबंधन के बारे में हमारे AI चैटबॉट से पूछें।',
    gsAddFirstCow: 'अपने पहले गाय को सिस्टम में जोड़ें',
    gsRecordHeat: 'गर्मी पता लगाने की घटना दर्ज करें',
    gsAskAi: 'AI से प्रजनन सलाह पूछें',
    gsConfigureSettings: 'अपने फार्म सेटिंग्स कॉन्फ़िगर करें',
    authTagline: 'स्मार्ट प्रजनन प्लेटफ़ॉर्म',
    authWelcomeBackTitle: 'वापस स्वागत है',
    authCreateAccountTitle: 'खाता बनाएं',
    authResetPasswordTitle: 'पासवर्ड रीसेट करें',
    authLoginSubtitle: 'अपने फार्म डैशबोर्ड तक पहुँचने के लिए साइन इन करें',
    authSignupSubtitle: 'AI-संचालित प्रजनन के साथ शुरू करें',
    authResetPasswordSubtitle: 'रीसेट लिंक पाने के लिए अपना ईमेल दर्ज करें',
    authFullName: 'पूरा नाम',
    authFullNamePlaceholder: 'राम किसान',
    authEmail: 'ईमेल',
    authEmailPlaceholder: 'you@farm.com',
    authPassword: 'पासवर्ड',
    authPasswordPlaceholder: '••••••••',
    authForgotPassword: 'पासवर्ड भूल गए?',
    authSending: 'भेज रहे हैं...',
    authSigningIn: 'साइन इन हो रहा है...',
    authCreatingAccount: 'खाता बन रहा है...',
    authSendResetLink: 'रीसेट लिंक भेजें',
    authSignIn: 'साइन इन',
    authSignUp: 'साइन अप',
    authCreateAccountBtn: 'खाता बनाएं',
    authBackToSignIn: '← साइन इन पर वापस',
    authNoAccount: 'खाता नहीं है?',
    authHaveAccount: 'पहले से खाता है?',
    settings: 'सेटिंग्स',

    noAbsentStaff: 'आज सभी कर्मचारी उपस्थित हैं',
    quickTips: 'त्वरित सुझाव',
    gettingStarted: 'शुरू करना',
    appearance: 'दिखावट',
    darkMode: 'डार्क मोड',
    toggleDarkTheme: 'डार्क थीम टॉगल करें',
    profile: 'प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    fullName: 'पूरा नाम',
    farmName: 'फार्म का नाम',
    farmLocation: 'फार्म का स्थान',
    saveChanges: 'परिवर्तन सहेजें',
    language: 'भाषा',
    selectLanguage: 'अपनी पसंदीदा भाषा चुनें',
    english: 'अंग्रेज़ी',
    spanish: 'स्पेनिश',
    french: 'फ्रेंच',
    swahili: 'स्वाहिली',
    tamil: 'तमिल',
    hindi: 'हिंदी',
    monthlyStock: 'मासिक स्टॉक आइटम',
    addItem: 'आइटम जोड़ें',
    noStockItems: 'इस महीने कोई स्टॉक आइटम नहीं',
    itemAdded: 'आइटम जोड़ा गया',
    itemUpdated: 'आइटम अपडेट किया गया',
    itemDeleted: 'आइटम हटाया गया',
    cowManagement: 'गाय प्रबंधन',
    heatDetection: 'गर्मी का पता लगाना',
    breedingCalendar: 'प्रजनन कैलेंडर',
    staffAttendance: 'कर्मचारी उपस्थिति',
    analytics: 'विश्लेषण',
    aiAssistant: 'AI सहायक',
    signOut: 'साइन आउट',
    signOutConfirmation: 'क्या आप वाकई साइन आउट करना चाहते हैं? अपने फार्म डेटा तक पहुंचने के लिए आपको फिर से साइन इन करना होगा।',
    askAnything: 'पशु प्रजनन के बारे में कुछ भी पूछें',
    howCanIHelp: 'मैं कैसे मदद कर सकता हूँ?',
    askAboutBreeding: 'प्रजनन, गर्मी का पता लगाने, या झुंड स्वास्थ्य के बारे में पूछें।',
    typeMessage: 'अपना संदेश टाइप करें...',
    send: 'भेजें',
    uploadImage: 'छवि अपलोड करें',
    recordAudio: 'ऑडियो रिकॉर्ड करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    processing: 'प्रोसेसिंग...',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    save: 'सहेजें',
    close: 'बंद करें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    export: 'निर्यात',
    import: 'आयात',
    refresh: 'रिफ्रेश',
    addCow: 'गाय जोड़ें',
    cowName: 'गाय का नाम',
    tagNumber: 'टैग नंबर',
    breed: 'नस्ल',
    dateOfBirth: 'जन्म तिथि',
    weight: 'वजन',
    status: 'स्थिति',
    notes: 'नोट्स',
    healthRecords: 'स्वास्थ्य रिकॉर्ड',
    milkProduction: 'दूध उत्पादन',
    currentlyInHeat: 'वर्तमान में गर्मी में',
    predictedHeat: 'अनुमानित गर्मी',
    lastHeatDate: 'अंतिम गर्मी तिथि',
    cycleLength: 'चक्र की लंबाई',
    upcomingEvents: 'आगामी कार्यक्रम',
    pastEvents: 'पिछले कार्यक्रम',
    addEvent: 'कार्यक्रम जोड़ें',
    eventType: 'कार्यक्रम प्रकार',
    eventDate: 'कार्यक्रम तिथि',
    staffMembers: 'कर्मचारी सदस्य',
    addStaff: 'कर्मचारी जोड़ें',
    staffName: 'कर्मचारी का नाम',
    role: 'भूमिका',
    phone: 'फोन',
    present: 'उपस्थित',
    absent: 'अनुपस्थित',
    checkIn: 'चेक इन',
    checkOut: 'चेक आउट',
    // Sensor Dashboard
    sensorDashboard: 'सेंसर डैशबोर्ड',
    lastUpdated: 'अंतिम अपडेट',
    online: 'ऑनलाइन',
    warning: 'चेतावनी',
    offline: 'ऑफलाइन',
    readings: 'रीडिंग',
    lastReading: 'अंतिम रीडिंग',
    time: 'समय',
    noDataReceived: 'कोई डेटा प्राप्त नहीं हुआ',
    activitySensor: 'गतिविधि सेंसर',
    temperatureSensor: 'तापमान सेंसर',
    weightSensor: 'वजन सेंसर',
    milkSensor: 'दूध सेंसर',
    pedometerSensor: 'पेडोमीटर',
    neckCollarSensor: 'गले का कॉलर',
    earTagSensor: 'कान का टैग',
    vaginalTempSensor: 'योनि तापमान सेंसर',
    rumenBolusSensor: 'रूमेन बोलस',
    mountingSensor: 'माउंटिंग सेंसर',
    tailHeadSensor: 'पूंछ सेंसर',
    ruminationSensor: 'जुगाली सेंसर',
    progesteroneSensor: 'प्रोजेस्टेरोन सेंसर',
    playVoice: 'आवाज चलाएं',
    stopVoice: 'आवाज रोकें',
    voiceEnabled: 'आवाज सक्षम',
    voiceDisabled: 'आवाज अक्षम',
    transcribing: 'लिख रहा है...',
    // App name
    appName: 'AI-FARM APP',
    // Settings
    settingsDesc: 'अपनी प्राथमिकताएं प्रबंधित करें',
    pushNotifications: 'पुश सूचनाएं',
    enableNotifications: 'सूचनाएं सक्षम करें',
    notificationsSupportedDesc: 'हीट डिटेक्शन, सेंसर अपडेट के लिए अलर्ट प्राप्त करें',
    notificationsNotSupported: 'इस ब्राउज़र में समर्थित नहीं',
    // Staff Attendance
    presentNow: 'अभी मौजूद',
    checkedOut: 'बाहर गया',
    notCheckedIn: 'पंजीकृत नहीं',
    totalStaff: 'कुल स्टाफ',
    todayAttendance: 'आज की उपस्थिति',
    // Calendar / Breeding
    heatDetected: 'हीट पता चला',
    insemination: 'गर्भाधान',
    pregnancyCheckEvent: 'गर्भावस्था जांच',
    expectedCalving: 'अपेक्षित बछड़ा',
    actualCalving: 'वास्तविक बछड़ा',
    selectADate: 'एक तारीख चुनें',
    optimalBreedingWindow: 'इष्टतम प्रजनन अवधि',
    scheduledEvents: 'निर्धारित कार्यक्रम',
    noEventsOnDate: 'इस तारीख पर कोई कार्यक्रम नहीं',
    addBreedingEvent: 'प्रजनन कार्यक्रम जोड़ें',
    selectCow: 'गाय चुनें',
    chooseCow: 'एक गाय चुनें',
    title: 'शीर्षक',
    optional: 'वैकल्पिक',
    description: 'विवरण',
    autoGeneratedIfEmpty: 'खाली होने पर स्वचालित रूप से जेनरेट',
    adding: 'जोड़ रहा है...',
    // Admin Dashboard
    adminDashboard: 'व्यवस्थापक डैशबोर्ड',
    adminDashboardDesc: 'सभी उपयोगकर्ताओं, गायों और फार्म डेटा का प्रबंधन करें',
    totalUsers: 'कुल उपयोगकर्ता',
    registeredUsers: 'पंजीकृत उपयोगकर्ता',
    acrossAllFarms: 'सभी फार्मों में',
    todayMilk: 'आज का दूध',
    totalProduction: 'कुल उत्पादन',
    activeLocations: 'सक्रिय स्थान',
    farmLocations: 'फार्म स्थान',
    users: 'उपयोगकर्ता',
    allUsers: 'सभी उपयोगकर्ता',
    allUsersDesc: 'सभी पंजीकृत उपयोगकर्ताओं और उनके फार्म विवरण देखें',
    allCows: 'सभी गायें',
    allCowsDesc: 'सभी फार्मों में सभी गायें देखें',
    allMilkProduction: 'सभी दूध उत्पादन',
    allMilkProductionDesc: 'सभी फार्मों से हाल के दूध उत्पादन रिकॉर्ड',
    adminName: 'नाम',
    adminFarmName: 'फार्म का नाम',
    adminLocation: 'स्थान',
    joinedDate: 'शामिल होने की तारीख',
    notSet: 'सेट नहीं',
    noUsersFound: 'कोई उपयोगकर्ता नहीं मिला',
    adminCowName: 'गाय का नाम',
    adminTagNumber: 'टैग नंबर',
    adminBreed: 'नस्ल',
    owner: 'मालिक',
    addedDate: 'जोड़ी गई तारीख',
    unknown: 'अज्ञात',
    adminQuantity: 'मात्रा',
    recordedAt: 'रिकॉर्ड किया गया',
    noMilkRecordsFound: 'कोई दूध रिकॉर्ड नहीं मिला',
    admin: 'व्यवस्थापक',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    // Check additional translations first
    if (cowManagementTranslations[language][key]) {
      return cowManagementTranslations[language][key];
    }
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
