import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'sw' | 'ta' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    settings: 'Settings',
    totalCows: 'Total Cows',
    healthy: 'Healthy',
    inHeat: 'In Heat',
    heatDetections: 'Heat Detections (7d)',
    absentStaff: 'Absent Staff',
    noAbsentStaff: 'All staff present today',
    quickTips: 'Quick Tips',
    gettingStarted: 'Getting Started',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    toggleDarkTheme: 'Toggle dark theme',
    profile: 'Profile',
    editProfile: 'Edit Profile',
    fullName: 'Full Name',
    farmName: 'Farm Name',
    farmLocation: 'Farm Location',
    saveChanges: 'Save Changes',
    language: 'Language',
    selectLanguage: 'Select your preferred language',
    english: 'English',
    spanish: 'Spanish',
    french: 'French',
    swahili: 'Swahili',
    tamil: 'Tamil',
    hindi: 'Hindi',
    monthlyStock: 'Monthly Stock Items',
    addItem: 'Add Item',
    noStockItems: 'No stock items for this month',
    itemAdded: 'Item added',
    itemUpdated: 'Item updated',
    itemDeleted: 'Item deleted',
    // Navigation
    cowManagement: 'Cow Management',
    heatDetection: 'Heat Detection',
    breedingCalendar: 'Breeding Calendar',
    staffAttendance: 'Staff Attendance',
    analytics: 'Analytics',
    aiAssistant: 'AI Assistant',
    signOut: 'Sign Out',
    signOutConfirmation: 'Are you sure you want to sign out? You will need to sign in again to access your farm data.',
    // AI Chat
    askAnything: 'Ask anything about cattle breeding',
    howCanIHelp: 'How can I help?',
    askAboutBreeding: 'Ask about breeding, heat detection, or herd health.',
    typeMessage: 'Type your message...',
    send: 'Send',
    uploadImage: 'Upload Image',
    recordAudio: 'Record Audio',
    stopRecording: 'Stop Recording',
    processing: 'Processing...',
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    save: 'Save',
    close: 'Close',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    refresh: 'Refresh',
    // Cow Management
    addCow: 'Add Cow',
    cowName: 'Cow Name',
    tagNumber: 'Tag Number',
    breed: 'Breed',
    dateOfBirth: 'Date of Birth',
    weight: 'Weight',
    status: 'Status',
    notes: 'Notes',
    healthRecords: 'Health Records',
    milkProduction: 'Milk Production',
    // Heat Detection
    currentlyInHeat: 'Currently in Heat',
    predictedHeat: 'Predicted Heat',
    lastHeatDate: 'Last Heat Date',
    cycleLength: 'Cycle Length',
    // Breeding
    upcomingEvents: 'Upcoming Events',
    pastEvents: 'Past Events',
    addEvent: 'Add Event',
    eventType: 'Event Type',
    eventDate: 'Event Date',
    // Staff
    staffMembers: 'Staff Members',
    addStaff: 'Add Staff',
    staffName: 'Staff Name',
    role: 'Role',
    phone: 'Phone',
    present: 'Present',
    absent: 'Absent',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    // Sensor Dashboard
    sensorDashboard: 'Sensor Dashboard',
    lastUpdated: 'Last updated',
    online: 'Online',
    warning: 'Warning',
    offline: 'Offline',
    readings: 'readings',
    lastReading: 'Last reading',
    time: 'Time',
    noDataReceived: 'No data received yet',
    activitySensor: 'Activity Sensor',
    temperatureSensor: 'Temperature Sensor',
    weightSensor: 'Weight Sensor',
    milkSensor: 'Milk Sensor',
    pedometerSensor: 'Pedometer',
    neckCollarSensor: 'Neck Collar',
    earTagSensor: 'Ear Tag Sensor',
    vaginalTempSensor: 'Vaginal Temp Sensor',
    rumenBolusSensor: 'Rumen Bolus',
    mountingSensor: 'Mounting Sensor',
    tailHeadSensor: 'Tail Head Sensor',
    ruminationSensor: 'Rumination Sensor',
    progesteroneSensor: 'Progesterone Sensor',
    // Voice features
    playVoice: 'Play voice response',
    stopVoice: 'Stop voice',
    voiceEnabled: 'Voice responses enabled',
    voiceDisabled: 'Voice responses disabled',
    transcribing: 'Transcribing...',
  },
  es: {
    dashboard: 'Panel',
    settings: 'Configuración',
    totalCows: 'Total de Vacas',
    healthy: 'Saludables',
    inHeat: 'En Celo',
    heatDetections: 'Detecciones de Celo (7d)',
    absentStaff: 'Personal Ausente',
    noAbsentStaff: 'Todo el personal presente hoy',
    quickTips: 'Consejos Rápidos',
    gettingStarted: 'Comenzar',
    appearance: 'Apariencia',
    darkMode: 'Modo Oscuro',
    toggleDarkTheme: 'Alternar tema oscuro',
    profile: 'Perfil',
    editProfile: 'Editar Perfil',
    fullName: 'Nombre Completo',
    farmName: 'Nombre de la Granja',
    farmLocation: 'Ubicación de la Granja',
    saveChanges: 'Guardar Cambios',
    language: 'Idioma',
    selectLanguage: 'Seleccione su idioma preferido',
    english: 'Inglés',
    spanish: 'Español',
    french: 'Francés',
    swahili: 'Suajili',
    tamil: 'Tamil',
    hindi: 'Hindi',
    monthlyStock: 'Artículos de Stock Mensual',
    addItem: 'Agregar Artículo',
    noStockItems: 'Sin artículos de stock este mes',
    itemAdded: 'Artículo agregado',
    itemUpdated: 'Artículo actualizado',
    itemDeleted: 'Artículo eliminado',
    cowManagement: 'Gestión de Vacas',
    heatDetection: 'Detección de Celo',
    breedingCalendar: 'Calendario de Cría',
    staffAttendance: 'Asistencia del Personal',
    analytics: 'Análisis',
    aiAssistant: 'Asistente IA',
    signOut: 'Cerrar Sesión',
    signOutConfirmation: '¿Está seguro de que desea cerrar sesión? Necesitará iniciar sesión de nuevo para acceder a los datos de su granja.',
    askAnything: 'Pregunte sobre cría de ganado',
    howCanIHelp: '¿Cómo puedo ayudar?',
    askAboutBreeding: 'Pregunte sobre cría, detección de celo o salud del rebaño.',
    typeMessage: 'Escriba su mensaje...',
    send: 'Enviar',
    uploadImage: 'Subir Imagen',
    recordAudio: 'Grabar Audio',
    stopRecording: 'Detener Grabación',
    processing: 'Procesando...',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    save: 'Guardar',
    close: 'Cerrar',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    refresh: 'Actualizar',
    addCow: 'Agregar Vaca',
    cowName: 'Nombre de la Vaca',
    tagNumber: 'Número de Etiqueta',
    breed: 'Raza',
    dateOfBirth: 'Fecha de Nacimiento',
    weight: 'Peso',
    status: 'Estado',
    notes: 'Notas',
    healthRecords: 'Registros de Salud',
    milkProduction: 'Producción de Leche',
    currentlyInHeat: 'Actualmente en Celo',
    predictedHeat: 'Celo Predicho',
    lastHeatDate: 'Última Fecha de Celo',
    cycleLength: 'Duración del Ciclo',
    upcomingEvents: 'Próximos Eventos',
    pastEvents: 'Eventos Pasados',
    addEvent: 'Agregar Evento',
    eventType: 'Tipo de Evento',
    eventDate: 'Fecha del Evento',
    staffMembers: 'Miembros del Personal',
    addStaff: 'Agregar Personal',
    staffName: 'Nombre del Personal',
    role: 'Rol',
    phone: 'Teléfono',
    present: 'Presente',
    absent: 'Ausente',
    checkIn: 'Registrar Entrada',
    checkOut: 'Registrar Salida',
    // Sensor Dashboard
    sensorDashboard: 'Panel de Sensores',
    lastUpdated: 'Última actualización',
    online: 'En línea',
    warning: 'Advertencia',
    offline: 'Desconectado',
    readings: 'lecturas',
    lastReading: 'Última lectura',
    time: 'Hora',
    noDataReceived: 'Sin datos recibidos',
    activitySensor: 'Sensor de Actividad',
    temperatureSensor: 'Sensor de Temperatura',
    weightSensor: 'Sensor de Peso',
    milkSensor: 'Sensor de Leche',
    pedometerSensor: 'Podómetro',
    neckCollarSensor: 'Collar de Cuello',
    earTagSensor: 'Etiqueta de Oreja',
    vaginalTempSensor: 'Sensor Temp. Vaginal',
    rumenBolusSensor: 'Bolo Ruminal',
    mountingSensor: 'Sensor de Monta',
    tailHeadSensor: 'Sensor de Cola',
    ruminationSensor: 'Sensor de Rumia',
    progesteroneSensor: 'Sensor de Progesterona',
    playVoice: 'Reproducir voz',
    stopVoice: 'Detener voz',
    voiceEnabled: 'Voz habilitada',
    voiceDisabled: 'Voz deshabilitada',
    transcribing: 'Transcribiendo...',
  },
  fr: {
    dashboard: 'Tableau de bord',
    settings: 'Paramètres',
    totalCows: 'Total des Vaches',
    healthy: 'En bonne santé',
    inHeat: 'En chaleur',
    heatDetections: 'Détections de chaleur (7j)',
    absentStaff: 'Personnel Absent',
    noAbsentStaff: 'Tout le personnel présent',
    quickTips: 'Conseils Rapides',
    gettingStarted: 'Commencer',
    appearance: 'Apparence',
    darkMode: 'Mode Sombre',
    toggleDarkTheme: 'Basculer le thème sombre',
    profile: 'Profil',
    editProfile: 'Modifier le Profil',
    fullName: 'Nom Complet',
    farmName: 'Nom de la Ferme',
    farmLocation: 'Emplacement de la Ferme',
    saveChanges: 'Enregistrer',
    language: 'Langue',
    selectLanguage: 'Sélectionnez votre langue préférée',
    english: 'Anglais',
    spanish: 'Espagnol',
    french: 'Français',
    swahili: 'Swahili',
    tamil: 'Tamoul',
    hindi: 'Hindi',
    monthlyStock: 'Articles de Stock Mensuel',
    addItem: 'Ajouter un Article',
    noStockItems: 'Aucun article de stock ce mois',
    itemAdded: 'Article ajouté',
    itemUpdated: 'Article mis à jour',
    itemDeleted: 'Article supprimé',
    cowManagement: 'Gestion des Vaches',
    heatDetection: 'Détection de Chaleur',
    breedingCalendar: 'Calendrier de Reproduction',
    staffAttendance: 'Présence du Personnel',
    analytics: 'Analyses',
    aiAssistant: 'Assistant IA',
    signOut: 'Déconnexion',
    signOutConfirmation: 'Êtes-vous sûr de vouloir vous déconnecter? Vous devrez vous reconnecter pour accéder aux données de votre ferme.',
    askAnything: 'Posez des questions sur l\'élevage bovin',
    howCanIHelp: 'Comment puis-je aider?',
    askAboutBreeding: 'Posez des questions sur l\'élevage, la détection de chaleur ou la santé du troupeau.',
    typeMessage: 'Tapez votre message...',
    send: 'Envoyer',
    uploadImage: 'Télécharger une Image',
    recordAudio: 'Enregistrer Audio',
    stopRecording: 'Arrêter l\'Enregistrement',
    processing: 'Traitement...',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    save: 'Enregistrer',
    close: 'Fermer',
    search: 'Rechercher',
    filter: 'Filtrer',
    export: 'Exporter',
    import: 'Importer',
    refresh: 'Actualiser',
    addCow: 'Ajouter une Vache',
    cowName: 'Nom de la Vache',
    tagNumber: 'Numéro d\'Étiquette',
    breed: 'Race',
    dateOfBirth: 'Date de Naissance',
    weight: 'Poids',
    status: 'Statut',
    notes: 'Notes',
    healthRecords: 'Dossiers de Santé',
    milkProduction: 'Production Laitière',
    currentlyInHeat: 'Actuellement en Chaleur',
    predictedHeat: 'Chaleur Prédite',
    lastHeatDate: 'Dernière Date de Chaleur',
    cycleLength: 'Durée du Cycle',
    upcomingEvents: 'Événements à Venir',
    pastEvents: 'Événements Passés',
    addEvent: 'Ajouter un Événement',
    eventType: 'Type d\'Événement',
    eventDate: 'Date de l\'Événement',
    staffMembers: 'Membres du Personnel',
    addStaff: 'Ajouter du Personnel',
    staffName: 'Nom du Personnel',
    role: 'Rôle',
    phone: 'Téléphone',
    present: 'Présent',
    absent: 'Absent',
    checkIn: 'Pointer l\'Entrée',
    checkOut: 'Pointer la Sortie',
    // Sensor Dashboard
    sensorDashboard: 'Tableau de Bord des Capteurs',
    lastUpdated: 'Dernière mise à jour',
    online: 'En ligne',
    warning: 'Avertissement',
    offline: 'Hors ligne',
    readings: 'lectures',
    lastReading: 'Dernière lecture',
    time: 'Heure',
    noDataReceived: 'Aucune donnée reçue',
    activitySensor: 'Capteur d\'Activité',
    temperatureSensor: 'Capteur de Température',
    weightSensor: 'Capteur de Poids',
    milkSensor: 'Capteur de Lait',
    pedometerSensor: 'Podomètre',
    neckCollarSensor: 'Collier de Cou',
    earTagSensor: 'Étiquette d\'Oreille',
    vaginalTempSensor: 'Capteur Temp. Vaginale',
    rumenBolusSensor: 'Bolus Ruminal',
    mountingSensor: 'Capteur de Monte',
    tailHeadSensor: 'Capteur de Queue',
    ruminationSensor: 'Capteur de Rumination',
    progesteroneSensor: 'Capteur de Progestérone',
    playVoice: 'Lire la voix',
    stopVoice: 'Arrêter la voix',
    voiceEnabled: 'Voix activée',
    voiceDisabled: 'Voix désactivée',
    transcribing: 'Transcription...',
  },
  sw: {
    dashboard: 'Dashibodi',
    settings: 'Mipangilio',
    totalCows: 'Jumla ya Ng\'ombe',
    healthy: 'Wenye Afya',
    inHeat: 'Katika Joto',
    heatDetections: 'Ugunduzi wa Joto (7d)',
    absentStaff: 'Wafanyakazi Wasiokuwepo',
    noAbsentStaff: 'Wafanyakazi wote wako leo',
    quickTips: 'Vidokezo vya Haraka',
    gettingStarted: 'Kuanza',
    appearance: 'Muonekano',
    darkMode: 'Hali ya Giza',
    toggleDarkTheme: 'Badilisha mandhari ya giza',
    profile: 'Wasifu',
    editProfile: 'Hariri Wasifu',
    fullName: 'Jina Kamili',
    farmName: 'Jina la Shamba',
    farmLocation: 'Mahali pa Shamba',
    saveChanges: 'Hifadhi Mabadiliko',
    language: 'Lugha',
    selectLanguage: 'Chagua lugha unayopendelea',
    english: 'Kiingereza',
    spanish: 'Kihispania',
    french: 'Kifaransa',
    swahili: 'Kiswahili',
    tamil: 'Kitamil',
    hindi: 'Kihindi',
    monthlyStock: 'Vitu vya Hifadhi vya Mwezi',
    addItem: 'Ongeza Kitu',
    noStockItems: 'Hakuna vitu vya hifadhi mwezi huu',
    itemAdded: 'Kitu kimeongezwa',
    itemUpdated: 'Kitu kimesasishwa',
    itemDeleted: 'Kitu kimefutwa',
    cowManagement: 'Usimamizi wa Ng\'ombe',
    heatDetection: 'Ugunduzi wa Joto',
    breedingCalendar: 'Kalenda ya Uzazi',
    staffAttendance: 'Mahudhurio ya Wafanyakazi',
    analytics: 'Uchambuzi',
    aiAssistant: 'Msaidizi wa AI',
    signOut: 'Ondoka',
    signOutConfirmation: 'Je, una uhakika unataka kuondoka? Utahitaji kuingia tena ili kufikia data ya shamba lako.',
    askAnything: 'Uliza chochote kuhusu ufugaji ng\'ombe',
    howCanIHelp: 'Nawezaje kusaidia?',
    askAboutBreeding: 'Uliza kuhusu uzazi, ugunduzi wa joto, au afya ya kundi.',
    typeMessage: 'Andika ujumbe wako...',
    send: 'Tuma',
    uploadImage: 'Pakia Picha',
    recordAudio: 'Rekodi Sauti',
    stopRecording: 'Simamisha Kurekodi',
    processing: 'Inachakata...',
    loading: 'Inapakia...',
    error: 'Hitilafu',
    success: 'Mafanikio',
    cancel: 'Ghairi',
    delete: 'Futa',
    edit: 'Hariri',
    add: 'Ongeza',
    save: 'Hifadhi',
    close: 'Funga',
    search: 'Tafuta',
    filter: 'Chuja',
    export: 'Hamisha',
    import: 'Ingiza',
    refresh: 'Onyesha upya',
    addCow: 'Ongeza Ng\'ombe',
    cowName: 'Jina la Ng\'ombe',
    tagNumber: 'Nambari ya Lebo',
    breed: 'Aina',
    dateOfBirth: 'Tarehe ya Kuzaliwa',
    weight: 'Uzito',
    status: 'Hali',
    notes: 'Maelezo',
    healthRecords: 'Rekodi za Afya',
    milkProduction: 'Uzalishaji wa Maziwa',
    currentlyInHeat: 'Kwa Sasa Katika Joto',
    predictedHeat: 'Joto Lililotabiriwa',
    lastHeatDate: 'Tarehe ya Joto la Mwisho',
    cycleLength: 'Urefu wa Mzunguko',
    upcomingEvents: 'Matukio Yanayokuja',
    pastEvents: 'Matukio Yaliyopita',
    addEvent: 'Ongeza Tukio',
    eventType: 'Aina ya Tukio',
    eventDate: 'Tarehe ya Tukio',
    staffMembers: 'Wanachama wa Wafanyakazi',
    addStaff: 'Ongeza Mfanyakazi',
    staffName: 'Jina la Mfanyakazi',
    role: 'Jukumu',
    phone: 'Simu',
    present: 'Yupo',
    absent: 'Hayupo',
    checkIn: 'Jisajili Kuingia',
    checkOut: 'Jisajili Kutoka',
    // Sensor Dashboard
    sensorDashboard: 'Dashibodi ya Sensori',
    lastUpdated: 'Iliyosasishwa mwisho',
    online: 'Mtandaoni',
    warning: 'Onyo',
    offline: 'Nje ya mtandao',
    readings: 'usomaji',
    lastReading: 'Usomaji wa mwisho',
    time: 'Wakati',
    noDataReceived: 'Hakuna data iliyopokelewa',
    activitySensor: 'Sensori ya Shughuli',
    temperatureSensor: 'Sensori ya Joto',
    weightSensor: 'Sensori ya Uzito',
    milkSensor: 'Sensori ya Maziwa',
    pedometerSensor: 'Pedometer',
    neckCollarSensor: 'Kola ya Shingo',
    earTagSensor: 'Tiketi ya Sikio',
    vaginalTempSensor: 'Sensori Joto la Uke',
    rumenBolusSensor: 'Bolus ya Tumbo',
    mountingSensor: 'Sensori ya Kupanda',
    tailHeadSensor: 'Sensori ya Mkia',
    ruminationSensor: 'Sensori ya Kucheuza',
    progesteroneSensor: 'Sensori ya Projesteroni',
    playVoice: 'Cheza sauti',
    stopVoice: 'Simamisha sauti',
    voiceEnabled: 'Sauti imewashwa',
    voiceDisabled: 'Sauti imezimwa',
    transcribing: 'Kuandika...',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    settings: 'அமைப்புகள்',
    totalCows: 'மொத்த மாடுகள்',
    healthy: 'ஆரோக்கியமான',
    inHeat: 'வெப்பத்தில்',
    heatDetections: 'வெப்ப கண்டறிதல் (7நா)',
    absentStaff: 'வராத ஊழியர்கள்',
    noAbsentStaff: 'இன்று அனைத்து ஊழியர்களும் உள்ளனர்',
    quickTips: 'விரைவு குறிப்புகள்',
    gettingStarted: 'தொடங்குதல்',
    appearance: 'தோற்றம்',
    darkMode: 'இருண்ட பயன்முறை',
    toggleDarkTheme: 'இருண்ட தீம் மாற்று',
    profile: 'சுயவிவரம்',
    editProfile: 'சுயவிவரத்தை திருத்து',
    fullName: 'முழு பெயர்',
    farmName: 'பண்ணை பெயர்',
    farmLocation: 'பண்ணை இடம்',
    saveChanges: 'மாற்றங்களை சேமி',
    language: 'மொழி',
    selectLanguage: 'உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்',
    english: 'ஆங்கிலம்',
    spanish: 'ஸ்பானிஷ்',
    french: 'பிரெஞ்சு',
    swahili: 'ஸ்வாஹிலி',
    tamil: 'தமிழ்',
    hindi: 'இந்தி',
    monthlyStock: 'மாதாந்திர இருப்பு பொருட்கள்',
    addItem: 'பொருள் சேர்',
    noStockItems: 'இந்த மாதம் இருப்பு பொருட்கள் இல்லை',
    itemAdded: 'பொருள் சேர்க்கப்பட்டது',
    itemUpdated: 'பொருள் புதுப்பிக்கப்பட்டது',
    itemDeleted: 'பொருள் நீக்கப்பட்டது',
    cowManagement: 'மாடு மேலாண்மை',
    heatDetection: 'வெப்ப கண்டறிதல்',
    breedingCalendar: 'இனப்பெருக்க நாட்காட்டி',
    staffAttendance: 'ஊழியர் வருகை',
    analytics: 'பகுப்பாய்வு',
    aiAssistant: 'AI உதவியாளர்',
    signOut: 'வெளியேறு',
    signOutConfirmation: 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா? உங்கள் பண்ணை தரவை அணுக மீண்டும் உள்நுழைய வேண்டும்.',
    askAnything: 'கால்நடை வளர்ப்பு பற்றி எதையும் கேளுங்கள்',
    howCanIHelp: 'நான் எப்படி உதவ முடியும்?',
    askAboutBreeding: 'இனப்பெருக்கம், வெப்ப கண்டறிதல் அல்லது மந்தை ஆரோக்கியம் பற்றி கேளுங்கள்.',
    typeMessage: 'உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...',
    send: 'அனுப்பு',
    uploadImage: 'படம் பதிவேற்று',
    recordAudio: 'ஒலி பதிவு',
    stopRecording: 'பதிவை நிறுத்து',
    processing: 'செயலாக்கம்...',
    loading: 'ஏற்றுகிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
    cancel: 'ரத்து செய்',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    add: 'சேர்',
    save: 'சேமி',
    close: 'மூடு',
    search: 'தேடு',
    filter: 'வடிகட்டு',
    export: 'ஏற்றுமதி',
    import: 'இறக்குமதி',
    refresh: 'புதுப்பி',
    addCow: 'மாடு சேர்',
    cowName: 'மாடு பெயர்',
    tagNumber: 'குறிச்சொல் எண்',
    breed: 'இனம்',
    dateOfBirth: 'பிறந்த தேதி',
    weight: 'எடை',
    status: 'நிலை',
    notes: 'குறிப்புகள்',
    healthRecords: 'சுகாதார பதிவுகள்',
    milkProduction: 'பால் உற்பத்தி',
    currentlyInHeat: 'தற்போது வெப்பத்தில்',
    predictedHeat: 'கணிக்கப்பட்ட வெப்பம்',
    lastHeatDate: 'கடைசி வெப்ப தேதி',
    cycleLength: 'சுழற்சி நீளம்',
    upcomingEvents: 'வரவிருக்கும் நிகழ்வுகள்',
    pastEvents: 'கடந்த நிகழ்வுகள்',
    addEvent: 'நிகழ்வு சேர்',
    eventType: 'நிகழ்வு வகை',
    eventDate: 'நிகழ்வு தேதி',
    staffMembers: 'ஊழியர்கள்',
    addStaff: 'ஊழியர் சேர்',
    staffName: 'ஊழியர் பெயர்',
    role: 'பங்கு',
    phone: 'தொலைபேசி',
    present: 'இருக்கிறார்',
    absent: 'இல்லை',
    checkIn: 'உள்நுழைவு',
    checkOut: 'வெளியேறுதல்',
    // Sensor Dashboard
    sensorDashboard: 'சென்சார் டாஷ்போர்டு',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    online: 'ஆன்லைன்',
    warning: 'எச்சரிக்கை',
    offline: 'ஆஃப்லைன்',
    readings: 'வாசிப்புகள்',
    lastReading: 'கடைசி வாசிப்பு',
    time: 'நேரம்',
    noDataReceived: 'தரவு பெறப்படவில்லை',
    activitySensor: 'செயல்பாட்டு சென்சார்',
    temperatureSensor: 'வெப்பநிலை சென்சார்',
    weightSensor: 'எடை சென்சார்',
    milkSensor: 'பால் சென்சார்',
    pedometerSensor: 'பெடோமீட்டர்',
    neckCollarSensor: 'கழுத்து பட்டை',
    earTagSensor: 'காது குறி',
    vaginalTempSensor: 'யோனி வெப்ப சென்சார்',
    rumenBolusSensor: 'ருமன் போலஸ்',
    mountingSensor: 'ஏறும் சென்சார்',
    tailHeadSensor: 'வால் தலை சென்சார்',
    ruminationSensor: 'அசை போடும் சென்சார்',
    progesteroneSensor: 'புரோஜெஸ்டிரோன் சென்சார்',
    playVoice: 'குரல் இயக்கு',
    stopVoice: 'குரல் நிறுத்து',
    voiceEnabled: 'குரல் இயக்கப்பட்டது',
    voiceDisabled: 'குரல் முடக்கப்பட்டது',
    transcribing: 'எழுதுகிறது...',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    settings: 'सेटिंग्स',
    totalCows: 'कुल गाय',
    healthy: 'स्वस्थ',
    inHeat: 'गर्मी में',
    heatDetections: 'गर्मी पता लगाना (7दि)',
    absentStaff: 'अनुपस्थित कर्मचारी',
    noAbsentStaff: 'आज सभी कर्मचारी उपस्थित हैं',
    quickTips: 'त्वरित सुझाव',
    gettingStarted: 'शुरू करना',
    appearance: 'दिखावट',
    darkMode: 'डार्क मोड',
    toggleDarkTheme: 'डार्क थीम टॉगल करें',
    profile: 'प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    fullName: 'पूरा नाम',
    farmName: 'फार्म का नाम',
    farmLocation: 'फार्म का स्थान',
    saveChanges: 'परिवर्तन सहेजें',
    language: 'भाषा',
    selectLanguage: 'अपनी पसंदीदा भाषा चुनें',
    english: 'अंग्रेज़ी',
    spanish: 'स्पेनिश',
    french: 'फ्रेंच',
    swahili: 'स्वाहिली',
    tamil: 'तमिल',
    hindi: 'हिंदी',
    monthlyStock: 'मासिक स्टॉक आइटम',
    addItem: 'आइटम जोड़ें',
    noStockItems: 'इस महीने कोई स्टॉक आइटम नहीं',
    itemAdded: 'आइटम जोड़ा गया',
    itemUpdated: 'आइटम अपडेट किया गया',
    itemDeleted: 'आइटम हटाया गया',
    cowManagement: 'गाय प्रबंधन',
    heatDetection: 'गर्मी का पता लगाना',
    breedingCalendar: 'प्रजनन कैलेंडर',
    staffAttendance: 'कर्मचारी उपस्थिति',
    analytics: 'विश्लेषण',
    aiAssistant: 'AI सहायक',
    signOut: 'साइन आउट',
    signOutConfirmation: 'क्या आप वाकई साइन आउट करना चाहते हैं? अपने फार्म डेटा तक पहुंचने के लिए आपको फिर से साइन इन करना होगा।',
    askAnything: 'पशु प्रजनन के बारे में कुछ भी पूछें',
    howCanIHelp: 'मैं कैसे मदद कर सकता हूँ?',
    askAboutBreeding: 'प्रजनन, गर्मी का पता लगाने, या झुंड स्वास्थ्य के बारे में पूछें।',
    typeMessage: 'अपना संदेश टाइप करें...',
    send: 'भेजें',
    uploadImage: 'छवि अपलोड करें',
    recordAudio: 'ऑडियो रिकॉर्ड करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    processing: 'प्रोसेसिंग...',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    save: 'सहेजें',
    close: 'बंद करें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    export: 'निर्यात',
    import: 'आयात',
    refresh: 'रिफ्रेश',
    addCow: 'गाय जोड़ें',
    cowName: 'गाय का नाम',
    tagNumber: 'टैग नंबर',
    breed: 'नस्ल',
    dateOfBirth: 'जन्म तिथि',
    weight: 'वजन',
    status: 'स्थिति',
    notes: 'नोट्स',
    healthRecords: 'स्वास्थ्य रिकॉर्ड',
    milkProduction: 'दूध उत्पादन',
    currentlyInHeat: 'वर्तमान में गर्मी में',
    predictedHeat: 'अनुमानित गर्मी',
    lastHeatDate: 'अंतिम गर्मी तिथि',
    cycleLength: 'चक्र की लंबाई',
    upcomingEvents: 'आगामी कार्यक्रम',
    pastEvents: 'पिछले कार्यक्रम',
    addEvent: 'कार्यक्रम जोड़ें',
    eventType: 'कार्यक्रम प्रकार',
    eventDate: 'कार्यक्रम तिथि',
    staffMembers: 'कर्मचारी सदस्य',
    addStaff: 'कर्मचारी जोड़ें',
    staffName: 'कर्मचारी का नाम',
    role: 'भूमिका',
    phone: 'फोन',
    present: 'उपस्थित',
    absent: 'अनुपस्थित',
    checkIn: 'चेक इन',
    checkOut: 'चेक आउट',
    // Sensor Dashboard
    sensorDashboard: 'सेंसर डैशबोर्ड',
    lastUpdated: 'अंतिम अपडेट',
    online: 'ऑनलाइन',
    warning: 'चेतावनी',
    offline: 'ऑफलाइन',
    readings: 'रीडिंग',
    lastReading: 'अंतिम रीडिंग',
    time: 'समय',
    noDataReceived: 'कोई डेटा प्राप्त नहीं हुआ',
    activitySensor: 'गतिविधि सेंसर',
    temperatureSensor: 'तापमान सेंसर',
    weightSensor: 'वजन सेंसर',
    milkSensor: 'दूध सेंसर',
    pedometerSensor: 'पेडोमीटर',
    neckCollarSensor: 'गले का कॉलर',
    earTagSensor: 'कान का टैग',
    vaginalTempSensor: 'योनि तापमान सेंसर',
    rumenBolusSensor: 'रूमेन बोलस',
    mountingSensor: 'माउंटिंग सेंसर',
    tailHeadSensor: 'पूंछ सेंसर',
    ruminationSensor: 'जुगाली सेंसर',
    progesteroneSensor: 'प्रोजेस्टेरोन सेंसर',
    playVoice: 'आवाज चलाएं',
    stopVoice: 'आवाज रोकें',
    voiceEnabled: 'आवाज सक्षम',
    voiceDisabled: 'आवाज अक्षम',
    transcribing: 'लिख रहा है...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
